Config = {}

Config.DiscordWebhookLogNormal = "https://discord.com/api/webhooks/656461661003186176/JqaqYp4SdgUtx1PsVKyuaoAayIFOpgtm2jEEZjD-9ZS_umwWvHWcWkOe2A3PGqLcYL2G" --write here global anticheat webhook

Config.DiscordWebhookLogPhoto = "https://discord.com/api/webhooks/656461661003186176/JqaqYp4SdgUtx1PsVKyuaoAayIFOpgtm2jEEZjD-9ZS_umwWvHWcWkOe2A3PGqLcYL2G" --write here webhook for photo

Config.DiscordWebhookLogBan = "https://discord.com/api/webhooks/656461661003186176/JqaqYp4SdgUtx1PsVKyuaoAayIFOpgtm2jEEZjD-9ZS_umwWvHWcWkOe2A3PGqLcYL2G" --write here webhook for bans

Config.BanKickMessageUrl = "https://discord.gg/c7WABYqa9K" -- write here url of your discord server

Config.ServerName = "Legacy-V" --write here server name 

Config.AntiCheatName = "💖 🛡️ RTX Anticheat 🛡️ 💖"

Config.BypassPerm = "rtxac.bypass"

Config.BanListPerm = "rtxac.banlist"

Config.AntiSpawnBlacklistedObjects = true

Config.AntiSpawnBlacklistedPeds = false

Config.AntiSpawnBlacklistedVehicles = true

Config.AntiSpawnMassObjects = true

Config.AntiSpawnMassPeds = true

Config.AntiSpawnMassVehicles = true

Config.DetectingTriggeringServerEvents = true

Config.BlockingExplosions = true

Config.BlockingBlacklistedMessages = true

Config.BlockingFakeMessages = true

Config.AntiBlacklistedPedChanger = true

Config.AntiBlacklistedWeaponUse = true

Config.AntiWeaponGive = true
Config.AntiWeaponGivePickupBypass = false -- activate if your server using weapon pickups

Config.AntiWeaponRemove = true

Config.AntiMaxHealtChanger = true

Config.SendingLogsToDiscord = true

Config.SendingBanLogsToDiscord = true

Config.KickHackers = true

Config.BanHackers = true

Config.BanSystem = true

Config.AntiExplosions = true

Config.CheaterAnnounceForEveryone = true

Config.SuspiciousResourcesStop = true

Config.ModMenuChecking = true

Config.PedTaskCanceling = true --if true its blocking for example player kicking from vehicles

Config.AntiBlacklistedPlayerNames = true

Config.GameTimerCheckingServer = 15000

Config.AntiAntiCheatStopCheckingServer = 10000

Config.EntityTablePlacerChecking = 5000

Config.PermissionChecking = 60000

Config.GlobalCheckingServer = 2000

Config.BlacklistedPlayerNames = { 
	{name = "Cheat"},
	{name = "https"},	
	{name = "http"},	
	{name = "<"},
	{name = "www."},
	{name = "script"},
	{name = "hack"},
	{name = "src"},
}

Config.AntiVPN = false
Config.VPNBypassOnlyIP = true
Config.OnlySpecifiedCountries = true

Config.VPNBypassAdresses = { 
	{playerip = "37.48.20.1024", playername = "Kanikuly", playersteam = "steam:11000013cc73739"},
}

Config.SpecifiedCountries = { 
	{country = "DE"},
	{country = "AT"},
	{country = "ch"},
}

Config.CheatsConfigure = { -- We recommend leaving the basic settings
	{typecheat = "spectating", ban = true},
	{typecheat = "godmode", ban = true},
	{typecheat = "maxarmor", ban = true},	
	{typecheat = "blacklistedkeys", ban = false},
	{typecheat = "cheatengine", ban = true},
	{typecheat = "nrcmethod", ban = true},
	{typecheat = "bcmethod", ban = true},
	{typecheat = "screenresult", ban = true},
	{typecheat = "injectioncommand", ban = true},
	{typecheat = "blips", ban = true},
	{typecheat = "antimodifer", ban = true},
	{typecheat = "antidamagechange", ban = true},
	{typecheat = "antiexplosivemelee", ban = true},
	{typecheat = "antiexplosiveweapon", ban = true},
	{typecheat = "speedhack", ban = false},
	{typecheat = "noclip", ban = true},
	{typecheat = "menucommandbl", ban = true},
	{typecheat = "clienteventexecute", ban = true},
	{typecheat = "gametime", ban = false},
	{typecheat = "stopresource", ban = true},
	{typecheat = "startresource", ban = true},
	{typecheat = "startrandomstringresource", ban = true},
	{typecheat = "maxhealth", ban = true},
	{typecheat = "pedspawnblacklisted", ban = true},
	{typecheat = "vehiclespawnblacklisted", ban = true},	
	{typecheat = "objectspawnblacklisted", ban = true},	
	{typecheat = "pedspawnmass", ban = true},
	{typecheat = "vehiclespawnmass", ban = true},	
	{typecheat = "objectspawnmass", ban = true},		
	{typecheat = "servereventexecute", ban = true},	
	{typecheat = "explosion", ban = true},	
	{typecheat = "blacklistedchatmessage", ban = false},	
	{typecheat = "fakechatmessage", ban = false},
	{typecheat = "anticheatturnoff", ban = true},	
	{typecheat = "superjump", ban = true},	
	{typecheat = "dangerousvariables", ban = true},	
	{typecheat = "injectedmenu", ban = true},	
	{typecheat = "suspiciousresource", ban = true},	
	{typecheat = "giveweapon", ban = true},	
	{typecheat = "removeweapon", ban = true},	
	{typecheat = "pedtask", ban = true},	
	{typecheat = "teleport", ban = true},	
	{typecheat = "invisible", ban = true},	
	{typecheat = "spawnvehicle", ban = true},	
	{typecheat = "nightvision", ban = true},
	{typecheat = "thermalvision", ban = true},	
	{typecheat = "vehicletuning", ban = true},	
	{typecheat = "aimbot", ban = true},	
	{typecheat = "esp", ban = true},
}

Config.Explosions = {
    [0] = { name = "Grenade", blacklisted = true},
    [1] = { name = "GrenadeLauncher", blacklisted = true},
    [2] = { name = "C4", blacklisted = true},
    [3] = { name = "Molotov", blacklisted = true},
    [4] = { name = "Rocket", blacklisted = true},
    [5] = { name = "TankShell", blacklisted = true},
    [6] = { name = "Hi_Octane", blacklisted = false},
    [7] = { name = "Car", blacklisted = false},
    [8] = { name = "Plance", blacklisted = false},
    [9] = { name = "PetrolPump", blacklisted = false},
    [10] = { name = "Bike", blacklisted = false},
    [11] = { name = "Dir_Steam", blacklisted = false},
    [12] = { name = "Dir_Flame", blacklisted = false},
    [13] = { name = "Dir_Water_Hydrant", blacklisted = false},
    [14] = { name = "Dir_Gas_Canister", blacklisted = false},
    [15] = { name = "Boat", blacklisted = false},
    [16] = { name = "Ship_Destroy", blacklisted = false},
    [17] = { name = "Truck", blacklisted = false},
    [18] = { name = "Bullet", blacklisted = false},
    [19] = { name = "SmokeGrenadeLauncher", blacklisted = false},
    [20] = { name = "SmokeGrenade", blacklisted = false},
    [21] = { name = "BZGAS", blacklisted = false},
    [22] = { name = "Flare", blacklisted = false},
    [23] = { name = "Gas_Canister", blacklisted = false},
    [24] = { name = "Extinguisher", blacklisted = false},
    [25] = { name = "Programmablear", blacklisted = true},
    [26] = { name = "Train", blacklisted = false},
    [27] = { name = "Barrel", blacklisted = false},
    [28] = { name = "PROPANE", blacklisted = false},
    [29] = { name = "Blimp", blacklisted = false},
    [30] = { name = "Dir_Flame_Explode", blacklisted = false},
    [31] = { name = "Tanker", blacklisted = false},
    [32] = { name = "PlaneRocket", blacklisted = true},
    [33] = { name = "VehicleBullet", blacklisted = true},
    [34] = { name = "Gas_Tank", blacklisted = false},
    [35] = { name = "FireWork", blacklisted = true},
    [36] = { name = "SnowBall", blacklisted = true},
    [37] = { name = "ProxMine", blacklisted = true},
    [38] = { name = "Valkyrie_Cannon" , blacklisted = true},
    [70] = { name = "AutoMizer", blacklisted = false}

}

Config.BlacklistedMessages = {
    "Bombay Menu",
    "Brutan Premium",
    "d0pamine | Nertigel#5391",
    "3You just got fucked by Luminous ^2Made by Plane#0007 ^1Purchase at ^4https://discord.gg/pQwzbdf",
    "Yo add me Fallen#0811",
    "d0pamine.xyz | discord.gg/fjBp55t",
    "Add me Baby Gangster#9026",
    "Yo add me Baby Gangster#9026",
    "EulenCheats",
    "Anti-Lynx",
    "Lynx 8",
    "Lynx 7",
    "lynxmenu",
    "HamHaxia",
    "Ham Mafia",
    "hammafia.com",
    "www.renalua.com",
    "Fallen#0811",
    ">:D Player Crash",  
    "34ByTe Community",
    "MARVIN menu",
    "BAGGY menu <3 https://discord.gg/AGxGDzg",
    "KoGuSzMENU <3 https://discord.gg/BbDMhJe",
    "Desudo menu <3 https://discord.gg/hkZgrv3",
    "You got raped by AlphaV",
    "TITO MODZ",
	'Desudo',
	'Brutan',
	'EulenCheats',
	"www.lynxmenu.com",
	"Ham Mafia",
	"Rena 8",
	"Xanax#0134",
	"lynxmenu.com",
	"Baran#8992",
	"iLostName#7138",
	"85.190.90.118",
	"AlphaV ~ 5391",
	"vjuton.pl",
	"EulenCheat",
	"Eulen",
	"Lynx",
	"lynxmenu.com - Cheats & Anti-Cheats!",
	"Soviet Bear",	
	"CK GANG",		
	"CK GANG!",
	"CK MAFIE",	
	"desudo",	
	"RedEngine",	
	"FiveMock",	
	"dopamine",	
	"Kubca",	
	"jsem cheater",	
	"cheatuju",	
	"NEGR",	
	"nigga",	
	"fortnitegang",	
	"ck bratva",	
	"ck terror",
	"CK BLOODS",
	"TAJNEMENUMenu",	
	"https://dc.xaries.pl",	
	"xaries.pl",	
	"SKAZA",	
	"SKAZA V500",	
	"xaries",	
	"xariesgang2",	
	"xariesgang3",	
	"xariesv2",	
	"xariesgang3",	
	"xaries gang 3*",	
	"ariesv1.0_1_1",	
	"BEE_1",	
	"renalua",	
	"Fallen",	
	"Xanax",	
	"MainMenu",	
	"SelfMenu",	
	"Baran",
	"iLostName",
	"LynX",
	"LynxX",
	"stt_prop_stunt_soccer_ball",
	"WarMenu",
	"INTERACTION MENU",
	"ARIES MENU",
	"XARIES",
	"666 GANG",
	"6666",
	"85.190.90.118",
	"Melon#1379",
	"hammafia.com",
	"TITOMODZ",
	"xseira",
	"AlphaV",
	"Soviet",
	"fefev",
	"ariesMenu",
	"AlikhanCheats",
	"FUCKFIVEMDOWNLOADHACKS",
	"DOWNLOADHACK",
	"fuckfivemdownloadhacks",
	"downloadhack",
	"werfvtghiouuiowrfetwerfio",
	"Lynx8",
	"LynxSeven",
	"KoGuSzEk",
	"lynxunknowncheats",
	"unknowncheats",
	"cheats",
	"cheat",
	"hack",
	"hacks",
	"BrutanPremium",
	"gaybuild",
	"TiagoMenu",
	"Dopamine",
	"MMenu",
	"nigmenu0001",
	"HamMafia",
	"b00mek",
	"LynxEvo",
    "SKAZAMENU",
}

Config.BlackListedObjects = {
	{name = "p_crahsed_heli_s"},
	{name = "prop_rock_4_big2"},
	{name = "prop_beachflag_le"},
	{name = "prop_fnclink_05crnr1"},
	{name = "xm_prop_x17_sub"},
	{name = "xs_prop_hamburgher_wl"},
	{name = "xs_prop_plastic_bottle_wl"},
	{name = "prop_windmill_01"},
	{name = "prop_windmill_01_I1"},
	{name = "prop_windmill_01_slod"},
    {name = "prop_windmill_01_slod2"},
    {name = "prop_vintage_pump"},
    {name = "p_spinning_anus_s"},
    {name = "prop_med_jet_01"},
    {name = "prop_box_wood06a"},
    {name = "prop_atm_01"},
    {name = "prop_juicestand"},
    {name = "bkr_prop_bkr_cashpile_04"},
    {name = "prop_bumper_car_01"},
    {name = "lts_prop_lts_elecbox_24"},
    {name = "hei_prop_crate_stack_01"},
    {name = "cs_x_rubweed"},
    {name = "des_fibstair_root"},
    {name = "p_dumpster_t"},
    {name = "p_oil_pjack_02_s"},
    {name = "hei_prop_heist_tug"},
    {name = "p_tram_crash_s"},
    {name = "prop_air_monhut_03_cr"},
    {name = "prop_carwash_roller_vert"},
    {name = "prop_cs_beachtowel_01"},
    {name = "prop_gas_pump_1d"},
    {name = "prop_gas_pump_1b"},
    {name = "prop_gas_pump_old3"},
    {name = "prop_gas_pump_1a"},
    {name = "prop_beach_fire"},
    {name = "prop_ld_toilet_01"},
    {name = "prop_ld_bomb_anim"},
    {name = "prop_ld_farm_couch01"},
    {name = "stt_prop_stunt_track_uturn"},
    {name = "stt_prop_stunt_track_turnice"},
    {name = "stt_prop_stunt_track_hill"},
    {name = "prop_gascyl_01a"},
    {name = "prop_gas_tank_01a"},
    {name = "prop_cs_dildo_01"},
    {name = "v_ilev_gc_weapons"},
    {name = "p_ferris_wheel_amo_l2"},
	{name = "stt_prop_ramp_adj_flip_m"},
	{name = "stt_prop_ramp_adj_flip_mb"},
	{name = "stt_prop_ramp_adj_flip_s"},
	{name = "stt_prop_ramp_adj_flip_sb"},
	{name = "stt_prop_ramp_adj_hloop"},
	{name = "stt_prop_ramp_adj_loop"},
	{name = "stt_prop_ramp_jump_l"},
	{name = "stt_prop_ramp_jump_m"},
	{name = "stt_prop_ramp_jump_s"},
	{name = "stt_prop_ramp_jump_xl"},
	{name = "stt_prop_ramp_jump_xs"},
	{name = "stt_prop_ramp_jump_xxl"},
	{name = "stt_prop_ramp_multi_loop_rb"},
	{name = "stt_prop_ramp_spiral_l"},
	{name = "stt_prop_stunt_soccer_ball"},
	{name = "stt_prop_ramp_spiral_l_l"},
	{name = "stt_prop_ramp_spiral_l_m"},
	{name = "stt_prop_ramp_spiral_l_s"},
	{name = "stt_prop_ramp_spiral_l_xxl"},
	{name = "stt_prop_ramp_spiral_m"},
	{name = "stt_prop_ramp_spiral_s"},
	{name = "stt_prop_ramp_spiral_xxl"},
	{name = "prop_container_01a"},
	{name = "stt_prop_stunt_domino"},
	{name = "stt_prop_stunt_jump15"},
	{name = "stt_prop_stunt_jump30"},
	{name = "stt_prop_stunt_jump45"},
	{name = "stt_prop_stunt_jump_l"},
	{name = "stt_prop_stunt_jump_lb"},
	{name = "stt_prop_stunt_jump_loop"},
	{name = "stt_prop_stunt_jump_m"},
	{name = "stt_prop_stunt_jump_mb"},
	{name = "stt_prop_stunt_jump_s"},
	{name = "stt_prop_stunt_jump_sb"},
	{name = "stt_prop_stunt_landing_zone_01"},
	{name = "stt_prop_stunt_ramp"},
	{name = "stt_prop_stunt_soccer_goal"},
	{name = "stt_prop_stunt_soccer_lball"},
	{name = "stt_prop_stunt_soccer_sball"},
	{name = "stt_prop_stunt_target"},
	{name = "stt_prop_stunt_small"},
	{name = "stt_prop_stunt_track_start"},
	{name = "stt_prop_stunt_track_slope45"},
	{name = "stt_prop_stunt_track_slope30"},
	{name = "stt_prop_stunt_track_slope15"},
	{name = "stt_prop_stunt_track_short"},
	{name = "stt_prop_stunt_track_dwuturn"},
	{name = "stt_prop_stunt_track_dwslope45"},
	{name = "stt_prop_stunt_track_funlng"},
	{name = "stt_prop_stunt_bowling_ball"},
    {name = "stt_prop_stunt_bowling_pin"},
    {name = "imp_prop_ship_01a"},
    {name = "dt1_tc_dufo_core"},
    {name = "db_apart_02_"},
    {name = "xm_prop_iaa_base_elevator"},
    {name = "xs_prop_chips_tube_wl"},
    {name = "prop_weed_01"},
    {name = "sr_prop_spec_tube_xxs_01a"},
    {name = "apa_mp_apa_y3_l2c"},
    {name = "sr_prop_spec_tube_crn_05a"},
    {name = "sr_prop_spec_tube_crn_30d_05a"},
    {name = "sr_prop_spec_tube_l_05a"},
    {name = "sr_prop_spec_tube_m_05a"},
    {name = "sr_prop_spec_tube_xxs_05a"},
    {name = "sr_prop_stunt_tube_crn_15d_05a"},
    {name = "sr_prop_stunt_tube_crn_5d_05a"},
    {name = "sr_prop_stunt_tube_xs_05a"},
    {name = "sr_prop_special_bblock_lrg11"},
    {name = "sr_prop_special_bblock_lrg2"},
    {name = "sr_prop_special_bblock_lrg3"},
    {name = "sr_prop_special_bblock_mdm1"},
    {name = "sr_prop_special_bblock_mdm2"},
    {name = "sr_prop_special_bblock_mdm3"},
    {name = "sr_prop_special_bblock_sml1"},
    {name = "sr_prop_special_bblock_sml2"},
    {name = "sr_prop_special_bblock_sml3"},
    {name = "sr_prop_special_bblock_xl1"},
    {name = "sr_prop_special_bblock_xl2"},
    {name = "sr_prop_special_bblock_xl3"},
    {name = "sr_prop_special_bblock_xl3_fixed"},
    {name = "sr_prop_sr_target_1_01a"},
    {name = "sr_prop_sr_target_2_04a"},
    {name = "sr_prop_sr_target_3_03a"},
    {name = "sr_prop_sr_target_5_01a"},
    {name = "sr_prop_sr_target_large_01a"},
    {name = "sr_prop_sr_target_long_01a"},
    {name = "sr_prop_sr_target_small_01a"},
    {name = "sr_prop_sr_target_small_02a"},
    {name = "sr_prop_sr_target_small_03a"},
    {name = "sr_prop_sr_target_small_04a"},
    {name = "sr_prop_sr_target_small_05a"},
    {name = "sr_prop_sr_target_small_06a"},
    {name = "sr_prop_sr_target_small_07a"},
    {name = "sr_prop_sr_target_trap_01a"},
    {name = "sr_prop_sr_target_trap_02a"},
    {name = "sr_prop_sr_track_block_01"},
    {name = "sr_prop_sr_track_wall"},
    {name = "sr_prop_sr_tube_end"},
    {name = "sr_prop_sr_tube_wall"},
    {name = "sr_prop_spec_target_b_01a"},
    {name = "sr_prop_spec_target_m_01a"},
    {name = "sr_prop_spec_target_s_01a"},
    {name = "sr_prop_spec_tube_refill"},
    {name = "sr_prop_track_refill"},
    {name = "sr_prop_track_refill_t1"},
    {name = "sr_prop_track_refill_t2"},
    {name = "sr_mp_spec_races_ammu_sign"},
    {name = "sr_mp_spec_races_blimp_sign"},
    {name = "sr_mp_spec_races_ron_sign"},
    {name = "sr_mp_spec_races_xero_sign"},
    {name = "sr_prop_sr_start_line_02"},
    {name = "sr_prop_track_straight_l_d15"},
    {name = "sr_prop_track_straight_l_d30"},
    {name = "sr_prop_track_straight_l_d45"},
    {name = "sr_prop_track_straight_l_d5"},
    {name = "sr_prop_track_straight_l_u15"},
    {name = "sr_prop_track_straight_l_u30"},
    {name = "sr_prop_track_straight_l_u45"},
    {name = "sr_prop_track_straight_l_u5"},
    {name = "sr_prop_spec_tube_crn_01a"},
    {name = "sr_prop_spec_tube_crn_30d_01a"},
    {name = "sr_prop_spec_tube_l_01a"},
    {name = "sr_prop_spec_tube_m_01a"},
    {name = "sr_prop_spec_tube_s_01a"},
    {name = "sr_prop_stunt_tube_crn_15d_01a"},
    {name = "sr_prop_stunt_tube_crn_5d_01a"},
    {name = "sr_prop_stunt_tube_crn2_01a"},
    {name = "sr_prop_stunt_tube_xs_01a"},
    {name = "sr_prop_spec_tube_crn_03a"},
    {name = "sr_prop_spec_tube_crn_30d_03a"},
    {name = "sr_prop_spec_tube_l_03a"},
    {name = "sr_prop_spec_tube_m_03a"},
    {name = "sr_prop_spec_tube_s_03a"},
    {name = "sr_prop_spec_tube_xxs_03a"},
    {name = "sr_prop_stunt_tube_crn_15d_03a"},
    {name = "sr_prop_stunt_tube_crn_5d_03a"},
    {name = "sr_prop_stunt_tube_crn2_03a"},
    {name = "sr_prop_stunt_tube_xs_03a"},
    {name = "sr_prop_spec_tube_crn_02a"},
    {name = "sr_prop_spec_tube_crn_30d_02a"},
    {name = "sr_prop_spec_tube_l_02a"},
    {name = "sr_prop_spec_tube_m_02a"},
    {name = "sr_prop_spec_tube_s_02a"},
    {name = "sr_prop_spec_tube_xxs_02a"},
    {name = "sr_prop_stunt_tube_crn_15d_02a"},
    {name = "sr_prop_stunt_tube_crn_5d_02a"},
    {name = "sr_prop_stunt_tube_crn2_02a"},
    {name = "sr_prop_stunt_tube_xs_02a"},
    {name = "sr_prop_spec_tube_crn_04a"},
    {name = "sr_prop_spec_tube_crn_30d_04a"},
    {name = "sr_prop_spec_tube_l_04a"},
    {name = "sr_prop_spec_tube_m_04a"},
    {name = "sr_prop_spec_tube_s_04a"},
    {name = "sr_prop_spec_tube_xxs_04a"},
    {name = "sr_prop_stunt_tube_crn_15d_04a"},
    {name = "sr_prop_stunt_tube_crn_5d_04a"},
    {name = "sr_prop_stunt_tube_crn2_04a"},
    {name = "sr_prop_stunt_tube_xs_04a"},
    {name = "stt_prop_race_tannoy"},
    {name = "stt_prop_speakerstack_01a"},
    {name = "stt_prop_flagpole_1c"},
    {name = "stt_prop_flagpole_1e"},
    {name = "stt_prop_flagpole_1d"},
    {name = "stt_prop_flagpole_1f"},
    {name = "stt_prop_flagpole_1a"},
    {name = "stt_prop_flagpole_1b"},
    {name = "stt_prop_flagpole_2a"},
    {name = "stt_prop_flagpole_2b"},
    {name = "stt_prop_flagpole_2c"},
    {name = "stt_prop_flagpole_2d"},
    {name = "stt_prop_flagpole_2e"},
    {name = "stt_prop_flagpole_2f"},
    {name = "stt_prop_corner_sign_01"},
    {name = "stt_prop_corner_sign_02"},
    {name = "stt_prop_corner_sign_03"},
    {name = "stt_prop_corner_sign_04"},
    {name = "stt_prop_corner_sign_05"},
    {name = "stt_prop_corner_sign_06"},
    {name = "stt_prop_corner_sign_07"},
    {name = "stt_prop_corner_sign_08"},
    {name = "stt_prop_corner_sign_09"},
    {name = "stt_prop_corner_sign_10"},
    {name = "stt_prop_corner_sign_11"},
    {name = "stt_prop_corner_sign_12"},
    {name = "stt_prop_corner_sign_13"},
    {name = "stt_prop_corner_sign_14"},
    {name = "stt_prop_hoop_constraction_01a"},
    {name = "stt_prop_hoop_small_01"},
    {name = "stt_prop_hoop_tyre_01a"},
    {name = "stt_prop_race_gantry_01"},
    {name = "stt_prop_race_start_line_01"},
    {name = "stt_prop_race_start_line_01b"},
    {name = "stt_prop_race_start_line_02b"},
    {name = "stt_prop_race_start_line_03"},
    {name = "stt_prop_race_start_line_03b"},
    {name = "stt_prop_sign_circuit_01"},
    {name = "stt_prop_sign_circuit_02"},
    {name = "stt_prop_sign_circuit_03"},
    {name = "stt_prop_sign_circuit_04"},
    {name = "stt_prop_sign_circuit_05"},
    {name = "stt_prop_sign_circuit_06"},
    {name = "stt_prop_sign_circuit_07"},
    {name = "stt_prop_sign_circuit_08"},
    {name = "stt_prop_sign_circuit_09"},
    {name = "stt_prop_sign_circuit_10"},
    {name = "stt_prop_sign_circuit_11"},
    {name = "stt_prop_sign_circuit_11b"},
    {name = "stt_prop_sign_circuit_12"},
    {name = "stt_prop_sign_circuit_13"},
    {name = "stt_prop_sign_circuit_13b"},
    {name = "stt_prop_sign_circuit_14"},
    {name = "stt_prop_sign_circuit_14b"},
    {name = "stt_prop_sign_circuit_15"},
    {name = "stt_prop_slow_down"},
    {name = "stt_prop_startline_gantry"},
    {name = "stt_prop_stunt_bblock_huge_01"},
    {name = "stt_prop_stunt_bblock_huge_02"},
    {name = "stt_prop_stunt_bblock_huge_03"},
    {name = "stt_prop_stunt_bblock_huge_04"},
    {name = "stt_prop_stunt_bblock_huge_05"},
    {name = "stt_prop_stunt_bblock_hump_01"},
    {name = "stt_prop_stunt_bblock_hump_02"},
    {name = "stt_prop_stunt_bblock_lrg1"},
    {name = "stt_prop_stunt_bblock_lrg2"},
    {name = "stt_prop_stunt_bblock_lrg3"},
    {name = "stt_prop_stunt_bblock_mdm1"},
    {name = "stt_prop_stunt_bblock_mdm2"},
    {name = "stt_prop_stunt_bblock_mdm3"},
    {name = "stt_prop_stunt_bblock_qp"},
    {name = "stt_prop_stunt_bblock_qp2"},
    {name = "stt_prop_stunt_bblock_qp3"},
    {name = "stt_prop_stunt_bblock_sml1"},
    {name = "stt_prop_stunt_bblock_sml2"},
    {name = "stt_prop_stunt_bblock_sml3"},
    {name = "stt_prop_stunt_bblock_xl1"},
    {name = "stt_prop_stunt_bblock_xl2"},
    {name = "stt_prop_stunt_bblock_xl3"},
    {name = "stt_prop_stunt_bowlpin_stand"},
    {name = "stt_prop_stunt_target_small"},
    {name = "stt_prop_stunt_track_bumps"},
    {name = "stt_prop_stunt_track_cutout"},
    {name = "stt_prop_stunt_track_dwlink"},
    {name = "stt_prop_stunt_track_dwlink_02"},
    {name = "stt_prop_stunt_track_dwsh15"},
    {name = "stt_prop_stunt_track_dwshort"},
    {name = "stt_prop_stunt_track_dwslope15"},
    {name = "stt_prop_stunt_track_dwslope30"},
    {name = "stt_prop_stunt_track_dwturn"},
    {name = "stt_prop_stunt_track_exshort"},
    {name = "stt_prop_stunt_track_fork"},
    {name = "stt_prop_stunt_track_funnel"},
    {name = "stt_prop_stunt_track_hill2"},
    {name = "stt_prop_stunt_track_jump"},
    {name = "stt_prop_stunt_track_link"},
    {name = "stt_prop_stunt_track_otake"},
    {name = "stt_prop_stunt_track_sh15"},
    {name = "stt_prop_stunt_track_sh30"},
    {name = "stt_prop_stunt_track_sh45"},
    {name = "stt_prop_stunt_track_sh45_a"},
    {name = "stt_prop_stunt_track_start_02"},
    {name = "stt_prop_stunt_track_straight"},
    {name = "stt_prop_stunt_track_straightice"},
    {name = "stt_prop_stunt_track_st_01"},
    {name = "stt_prop_stunt_track_st_02"},
    {name = "stt_prop_stunt_track_turn"},
    {name = "stt_prop_stunt_tube_crn"},
    {name = "stt_prop_stunt_tube_crn2"},
    {name = "stt_prop_stunt_tube_crn_15d"},
    {name = "stt_prop_stunt_tube_crn_30d"},
    {name = "stt_prop_stunt_tube_crn_5d"},
    {name = "stt_prop_stunt_tube_cross"},
    {name = "stt_prop_stunt_tube_end"},
    {name = "stt_prop_stunt_tube_ent"},
    {name = "stt_prop_stunt_tube_fn_01"},
    {name = "stt_prop_stunt_tube_fn_02"},
    {name = "stt_prop_stunt_tube_fn_03"},
    {name = "stt_prop_stunt_tube_fn_04"},
    {name = "stt_prop_stunt_tube_fn_05"},
    {name = "stt_prop_stunt_tube_fork"},
    {name = "stt_prop_stunt_tube_gap_01"},
    {name = "stt_prop_stunt_tube_gap_02"},
    {name = "stt_prop_stunt_tube_gap_03"},
    {name = "stt_prop_stunt_tube_hg"},
    {name = "stt_prop_stunt_tube_jmp"},
    {name = "stt_prop_stunt_tube_jmp2"},
    {name = "stt_prop_stunt_tube_l"},
    {name = "stt_prop_stunt_tube_m"},
    {name = "stt_prop_stunt_tube_qg"},
    {name = "stt_prop_stunt_tube_s"},
    {name = "stt_prop_stunt_tube_speed"},
    {name = "stt_prop_stunt_tube_speeda"},
    {name = "stt_prop_stunt_tube_speedb"},
    {name = "stt_prop_stunt_tube_xs"},
    {name = "stt_prop_stunt_tube_xxs"},
    {name = "stt_prop_stunt_wideramp"},
    {name = "stt_prop_track_bend2_bar_l"},
    {name = "stt_prop_track_bend2_bar_l_b"},
    {name = "stt_prop_track_bend2_l"},
    {name = "stt_prop_track_bend2_l_b"},
    {name = "stt_prop_track_bend_15d"},
    {name = "stt_prop_track_bend_15d_bar"},
    {name = "stt_prop_track_bend_180d"},
    {name = "stt_prop_track_bend_180d_bar"},
    {name = "stt_prop_track_bend_30d"},
    {name = "stt_prop_track_bend_30d_bar"},
    {name = "stt_prop_track_bend_5d"},
    {name = "stt_prop_track_bend_5d_bar"},
    {name = "stt_prop_track_bend_bar_l"},
    {name = "stt_prop_track_bend_bar_l_b"},
    {name = "stt_prop_track_bend_bar_m"},
    {name = "stt_prop_track_bend_l"},
    {name = "stt_prop_track_bend_l_b"},
    {name = "stt_prop_track_bend_m"},
    {name = "stt_prop_track_block_01"},
    {name = "stt_prop_track_block_02"},
    {name = "stt_prop_track_block_03"},
    {name = "stt_prop_track_chicane_l"},
    {name = "stt_prop_track_chicane_l_02"},
    {name = "stt_prop_track_chicane_r"},
    {name = "stt_prop_track_chicane_r_02"},
    {name = "stt_prop_track_cross"},
    {name = "stt_prop_track_cross_bar"},
    {name = "stt_prop_track_fork"},
    {name = "stt_prop_track_fork_bar"},
    {name = "stt_prop_track_funnel"},
    {name = "stt_prop_track_funnel_ads_01a"},
    {name = "stt_prop_track_funnel_ads_01b"},
    {name = "stt_prop_track_funnel_ads_01c"},
    {name = "stt_prop_track_jump_01a"},
    {name = "stt_prop_track_jump_01b"},
    {name = "stt_prop_track_jump_01c"},
    {name = "stt_prop_track_jump_02a"},
    {name = "stt_prop_track_jump_02b"},
    {name = "stt_prop_track_jump_02c"},
    {name = "stt_prop_track_link"},
    {name = "stt_prop_track_slowdown"},
    {name = "stt_prop_track_slowdown_t1"},
    {name = "stt_prop_track_slowdown_t2"},
    {name = "stt_prop_track_speedup"},
    {name = "stt_prop_track_speedup_t1"},
    {name = "stt_prop_track_speedup_t2"},
    {name = "stt_prop_track_start_02"},
    {name = "stt_prop_track_start"},
    {name = "stt_prop_track_stop_sign"},
    {name = "stt_prop_track_straight_bar_l"},
    {name = "stt_prop_track_straight_bar_m"},
    {name = "stt_prop_track_straight_bar_s"},
    {name = "stt_prop_track_straight_l"},
    {name = "stt_prop_track_straight_lm"},
    {name = "stt_prop_track_straight_lm_bar"},
    {name = "stt_prop_track_straight_m"},
    {name = "stt_prop_track_straight_s"},
    {name = "stt_prop_track_tube_01"},
    {name = "stt_prop_track_tube_02"},
    {name = "stt_prop_tyre_wall_01"},
    {name = "stt_prop_tyre_wall_010"},
    {name = "stt_prop_tyre_wall_011"},
    {name = "stt_prop_tyre_wall_012"},
    {name = "stt_prop_tyre_wall_013"},
    {name = "stt_prop_tyre_wall_014"},
    {name = "stt_prop_tyre_wall_015"},
    {name = "stt_prop_tyre_wall_02"},
    {name = "stt_prop_tyre_wall_03"},
    {name = "stt_prop_tyre_wall_05"},
    {name = "stt_prop_tyre_wall_06"},
    {name = "stt_prop_tyre_wall_07"},
    {name = "stt_prop_tyre_wall_08"},
    {name = "stt_prop_tyre_wall_09"},
    {name = "stt_prop_tyre_wall_0l010"},
    {name = "stt_prop_tyre_wall_0l012"},
    {name = "stt_prop_tyre_wall_0l013"},
    {name = "stt_prop_tyre_wall_0l014"},
    {name = "stt_prop_tyre_wall_0l015"},
    {name = "stt_prop_tyre_wall_0l018"},
    {name = "stt_prop_tyre_wall_0l019"},
    {name = "stt_prop_tyre_wall_0l020"},
    {name = "stt_prop_tyre_wall_0l04"},
    {name = "stt_prop_tyre_wall_0l05"},
    {name = "stt_prop_tyre_wall_0l06"},
    {name = "stt_prop_tyre_wall_0l07"},
    {name = "stt_prop_tyre_wall_0l08"},
    {name = "stt_prop_tyre_wall_0l1"},
    {name = "stt_prop_tyre_wall_0l16"},
    {name = "stt_prop_tyre_wall_0l17"},
    {name = "stt_prop_tyre_wall_0l2"},
    {name = "stt_prop_tyre_wall_0l3"},
    {name = "stt_prop_tyre_wall_0r010"},
    {name = "stt_prop_tyre_wall_0r011"},
    {name = "stt_prop_tyre_wall_0r012"},
    {name = "stt_prop_tyre_wall_0r013"},
    {name = "stt_prop_tyre_wall_0r014"},
    {name = "stt_prop_tyre_wall_0r015"},
    {name = "stt_prop_tyre_wall_0r016"},
    {name = "stt_prop_tyre_wall_0r017"},
    {name = "stt_prop_tyre_wall_0r018"},
    {name = "stt_prop_tyre_wall_0r019"},
    {name = "stt_prop_tyre_wall_0r04"},
    {name = "stt_prop_tyre_wall_0r05"},
    {name = "stt_prop_tyre_wall_0r06"},
    {name = "stt_prop_tyre_wall_0r07"},
    {name = "stt_prop_tyre_wall_0r08"},
    {name = "stt_prop_tyre_wall_0r09"},
    {name = "stt_prop_tyre_wall_0r1"},
    {name = "stt_prop_tyre_wall_0r2"},
    {name = "stt_prop_tyre_wall_0r3"},
    {name = "stt_prop_wallride_01"},
    {name = "stt_prop_wallride_01b"},
    {name = "stt_prop_wallride_02"},
    {name = "stt_prop_wallride_02b"},
    {name = "stt_prop_wallride_04"},
    {name = "stt_prop_wallride_05"},
    {name = "stt_prop_wallride_05b"},
    {name = "stt_prop_wallride_45l"},
    {name = "stt_prop_wallride_45la"},
    {name = "stt_prop_wallride_45r"},
    {name = "stt_prop_wallride_45ra"},
    {name = "stt_prop_wallride_90l"},
    {name = "stt_prop_wallride_90lb"},
    {name = "stt_prop_wallride_90r"},
    {name = "stt_prop_wallride_90rb"},
    {name = "apa_MP_Apa_Yacht"},
    {name = "apa_mp_apa_y1_l1a"},
    {name = "apa_mp_apa_y1_l1b"},
    {name = "apa_mp_apa_y1_l1c"},
    {name = "apa_mp_apa_y1_l1d"},
    {name = "apa_mp_apa_y2_l1a"},
    {name = "apa_mp_apa_y2_l1b"},
    {name = "apa_mp_apa_y2_l1c"},
    {name = "apa_mp_apa_y2_l1d"},
    {name = "apa_mp_apa_y3_l1a"},
    {name = "apa_mp_apa_y3_l1b"},
    {name = "apa_mp_apa_y3_l1c"},
    {name = "apa_mp_apa_y3_l1d"},
    {name = "apa_mp_apa_yacht_o1_rail_a"},
    {name = "apa_mp_apa_yacht_o1_rail_b"},
    {name = "apa_mp_apa_yacht_o2_rail_a"},
    {name = "apa_mp_apa_yacht_o2_rail_b"},
    {name = "apa_mp_apa_yacht_o3_rail_a"},
    {name = "apa_mp_apa_yacht_o3_rail_b"},
    {name = "apa_mp_apa_yacht_option1"},
    {name = "apa_mp_apa_yacht_option1_cola"},
    {name = "apa_mp_apa_yacht_option2"},
    {name = "apa_mp_apa_yacht_option2_cola"},
    {name = "apa_mp_apa_yacht_option2_colb"},
    {name = "apa_mp_apa_yacht_option3"},
    {name = "apa_mp_apa_yacht_option3_cola"},
    {name = "apa_mp_apa_yacht_option3_colb"},
    {name = "apa_mp_apa_yacht_option3_colc"},
    {name = "apa_mp_apa_yacht_option3_cold"},
    {name = "apa_mp_apa_yacht_option3_cole"},
    {name = "apa_MP_Apa_Yacht_Jacuzzi_Cam"},
    {name = "apa_mp_apa_yacht_jacuzzi_ripple003"},
    {name = "apa_mp_apa_yacht_jacuzzi_ripple1"},
    {name = "apa_mp_apa_yacht_radar_01a"},
    {name = "apa_MP_Apa_Yacht_Win"},
	{name = "prop_doghouse_01"},
}

Config.BlackListedPeds = {
	{name = "s_m_y_swat_01"},
	{name = "u_m_y_juggernaut_01"},
	{name = "s_m_m_movalien_01"},
	{name = "a_m_y_acult_02"},
	{name = "a_m_o_acult_02"},
	{name = "a_m_m_acult_02"},
	{name = "u_m_m_streetart_01"},
	{name = "u_m_y_rsranger_01"},
	{name = "u_m_y_pogo_01"},
	{name = "ig_orleans"},
	{name = "cs_orleans"},
	{name = "mp_m_niko_01"},
	{name = "s_m_m_movspace_01"},
	{name = "mp_m_marston_01"},
	{name = "ig_johnnyklebitz"},
	{name = "a_c_hen"},
	{name = "a_c_sharkhammer"},
	{name = "a_c_fish"},
	{name = "a_c_deer"},
	{name = "a_c_cormorant"},
	{name = "a_c_cow"},
	{name = "a_c_crow"},
	{name = "a_c_chickenhawk"},
	{name = "a_c_chimp"},
	{name = "cs_bradcadaver"},
	{name = "a_c_boar"},
	{name = "u_f_m_drowned_01"},
	{name = "a_c_sharktiger"},
	{name = "a_c_seagull"},
	{name = "a_c_rat"},
	{name = "a_c_rhesus"},
	{name = "a_c_rabbit_01"},
	{name = "a_c_pig"},
	{name = "a_c_humpback"},	
	{name = "u_m_y_zombie_01"},
	{name = "a_m_o_acult_01"},
	{name = "a_m_m_acult_01"},
	{name = "a_m_y_acult_01"},
	{name = "ig_wade"},
	{name = "s_m_m_paramedic_01"},
	{name = "s_m_y_fireman_01"},
	{name = "a_m_y_mexthug_01"},
	{name = "a_c_cat_01"},	
	{name = "a_c_coyote"},
	{name = "a_c_dolphin"},
	{name = "a_c_killerwhale"},
	{name = "a_c_mtlion"},	
}

Config.BlackListedPedsSpawn = {
	{name = "u_m_y_juggernaut_01"},
	{name = "s_m_m_movalien_01"},
	{name = "a_m_y_acult_02"},
	{name = "a_m_o_acult_02"},
	{name = "a_m_m_acult_02"},
	{name = "u_m_m_streetart_01"},
	{name = "u_m_y_rsranger_01"},
	{name = "u_m_y_pogo_01"},
	{name = "mp_m_niko_01"},
	{name = "s_m_m_movspace_01"},
	{name = "mp_m_marston_01"},
	{name = "ig_johnnyklebitz"},
	{name = "a_c_chimp"},
	{name = "cs_bradcadaver"},
	{name = "u_m_y_zombie_01"},
	{name = "a_m_o_acult_01"},
	{name = "a_m_m_acult_01"},
	{name = "a_m_y_acult_01"},
	{name = "ig_wade"},
	{name = "a_m_y_mexthug_01"},
}

Config.BlacklistedWeapons = {
    [`weapon_rpg`] = 'weapon_rpg',
    [`weapon_heavysniper`] = 'weapon_heavysniper',
    [`weapon_marksmanrifle_mk2`] = 'weapon_marksmanrifle_mk2',
    [`weapon_marksmanrifle`] = 'weapon_marksmanrifle',
    [`weapon_grenadelauncher`] = 'weapon_grenadelauncher',
    [`weapon_grenadelauncher_smoke`] = 'weapon_grenadelauncher_smoke',
    [`weapon_minigun`] = 'weapon_minigun',
    [`weapon_firework`] = 'weapon_firework',
    [`weapon_railgun`] = 'weapon_railgun',
    [`weapon_hominglauncher`] = 'weapon_hominglauncher',
    [`weapon_compactlauncher`] = 'weapon_compactlauncher',
    [`weapon_rayminigun`] = 'weapon_rayminigun',
    [`weapon_grenade`] = 'weapon_grenade',
    [`weapon_bzgas`] = 'weapon_bzgas',
    [`weapon_molotov`] = 'weapon_molotov',
    [`weapon_stickybomb`] = 'weapon_stickybomb',
    [`weapon_proxmine`] = 'weapon_proxmine',
    [`weapon_pipebomb`] = 'weapon_pipebomb',
    [`weapon_smokegrenader`] = 'weapon_smokegrenade',
    [`weapon_rocket`] = 'weapon_rocket',
    [`weapon_explosion`] = 'weapon_explosion',
    [`weapon_flare`] = 'weapon_flare',
    [`weapon_stinger`] = 'weapon_stinger',
    [`weapon_musket`] = 'weapon_musket',
    [`weapon_smg`] = 'weapon_smg'
}

Config.BlackListedVehicles = {
	{name = "cargoplane"},
	{name = "cerberus"},
	{name = "cerberus2"},
	{name = "cerberus3"},
	{name = "hauler2"},
	{name = "phantom2"},
	{name = "terbyte"},
	{name = "issi4"},
	{name = "issi5"},
	{name = "issi6"},
	{name = "akula"},
	{name = "annihilator"},
	{name = "buzzard"},
	{name = "hunter"},
	{name = "savage"},
	{name = "apc"},
	{name = "barrage"},
	{name = "chernobog"},
	{name = "halftrack"},
	{name = "khanjali"},
	{name = "minitank"},
	{name = "rhino"},
	{name = "scarab"},
	{name = "scarab2"},
	{name = "scarab3"},
	{name = "thruster"},
	{name = "trailersmall2"},
	{name = "oppressor"},
	{name = "oppressor2"},
	{name = "dominator4"},
	{name = "dominator5"},
	{name = "dominator6"},
	{name = "dukes2"},
	{name = "impaler2"},
	{name = "impaler3"},
	{name = "impaler4"},
	{name = "imperator"},
	{name = "imperator2"},
	{name = "imperator3"},
	{name = "bruiser"},
	{name = "bruiser2"},
	{name = "bruiser3"},
	{name = "brutus"},
	{name = "brutus2"},
	{name = "brutus3"},
	{name = "caracara"},
	{name = "dune4"},
	{name = "dune5"},
	{name = "insurgent"},
	{name = "insurgent3"},
	{name = "menacer"},
	{name = "nightshark"},
	{name = "technical"},
	{name = "technical2"},
	{name = "technical3"},
	{name = "zhaba"},
	{name = "avenger"},
	{name = "avenger2"},
	{name = "besra"},
	{name = "jet"},
	{name = "hydra"},
	{name = "strikeforce"},
	{name = "titan"},
	{name = "volatol"},
	{name = "limo2"},
	{name = "zr380"},
	{name = "zr3802"},
	{name = "zr3803"},
	{name = "deluxo"},
	{name = "vigilante"},
	{name = "boxville5"},
	{name = "kuruma2"},
	{name = "scramjet"},
}

Config.BlackListedServerEvents = {
	"8321hiue89js",
	"adminmenu:allowall",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"AdminMenu:giveDirtyMoney",
	"Tem2LPs5Para5dCyjuHm87y2catFkMpV",
	"dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
	"antilynx8:anticheat",
	"antilynxr4:detect",
	"antilynxr6:detection",
	"ynx8:anticheat",
	"antilynx8r4a:anticheat",
	"lynx8:anticheat",
	"AntiLynxR4:kick",
	"AntiLynxR4:log",
	"bank:deposit",
	"bank:withdraw",
	"Banca:deposit",
	"Banca:withdraw",
	"BsCuff:Cuff696999",
	"CheckHandcuff",
	"cuffServer",
	"cuffGranted",
	"DiscordBot:playerDied",
	"DFWM:adminmenuenable",
	"DFWM:askAwake",
	"DFWM:checkup",
	"DFWM:cleanareaentity",
	"DFWM:cleanareapeds",
	"DFWM:cleanareaveh",
	"DFWM:enable",
	"DFWM:invalid",
	"DFWM:log",
	"DFWM:openmenu",
	"DFWM:spectate",
	"DFWM:ViolationDetected",
	"dmv:success",
	"eden_garage:payhealth",
	"ems:revive",
	"esx_ambulancejob:revive",
--	"esx_ambulancejob:setDeathStatus",
--	"esx_billing:sendBill",
	"esx_banksecurity:pay",
	"esx_blanchisseur:startWhitening",
	"esx_carthief:alertcops",
	"esx_carthief:pay",
--	"esx_dmvschool:addLicense",
--	"esx_dmvschool:pay",
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startSellWeed",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startSellCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startSellMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startTransformOpium",
	"esx_drugs:startSellOpium",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopTransformWeed",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:stopSellOpium",
	"esx:enterpolicecar",
	"esx_fueldelivery:pay",
--	"esx:giveInventoryItem",
	"esx_garbagejob:pay",
	"esx_godirtyjob:pay",
	"esx_gopostaljob:pay",
	"esx_handcuffs:cuffing",
	"esx_jail:sendToJail",
	"esx_jail:unjailQuest",
	"esx_jailer:sendToJail",
	"esx_jailer:unjailTime",
	"esx_jobs:caution",
	"esx_mecanojob:onNPCJobCompleted",
	"esx_mechanicjob:startHarvest",
	"esx_mechanicjob:startCraft",
	"esx_pizza:pay",
--	"esx_policejob:handcuff",
	"esx_policejob:requestarrest",
	"esx-qalle-jail:jailPlayer",
	"esx-qalle-jail:jailPlayerNew",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_ranger:pay",
--	"esx:removeInventoryItem",
	"esx_truckerjob:pay",
	"esx_skin:responseSaveSkin",
	"esx_slotmachine:sv:2",
	"esx_society:getOnlinePlayers",
	"esx_society:setJob",
	"esx_vehicleshop:setVehicleOwned",
	"hentailover:xdlol",
	"JailUpdate",
	"js:jailuser",
	"js:removejailtime",
--	"LegacyFuel:PayFuel",
	"ljail:jailplayer",
	"lscustoms:payGarage",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"mellotrainer:s_adminKill",
	"NB:destituerplayer",
	"NB:recruterplayer",
	"OG_cuffs:cuffCheckNearest",
	"paramedic:revive",
	"police:cuffGranted",
	"unCuffServer",
	"uncuffGranted",
	"vrp_slotmachine:server:2",
	"whoapd:revive",
	"gcPhone:_internalAddMessageDFWM",
	"gcPhone:tchat_channelDFWM",
	"esx_vehicleshop:setVehicleOwnedDFWM",
	"esx_mafiajob:confiscateDFWMPlayerItem",
	"_chat:messageEntDFWMered",
	"lscustoms:pDFWMayGarage",
	"vrp_slotmachDFWMine:server:2",
	"Banca:dDFWMeposit",
	"bank:depDFWMosit",
	"esx_jobs:caDFWMution",
	"give_back",
	"esx_fueldDFWMelivery:pay",
	"esx_carthDFWMief:pay",
	"esx_godiDFWMrtyjob:pay",
	"esx_pizza:pDFWMay",
	"esx_ranger:pDFWMay",
	"esx_garbageDFWMjob:pay",
	"esx_truckDFWMerjob:pay",
	"AdminMeDFWMnu:giveBank",
	"AdminMDFWMenu:giveCash",
	"esx_goDFWMpostaljob:pay",
	"esx_baDFWMnksecurity:pay",
	"esx_sloDFWMtmachine:sv:2",
	"esx:giDFWMveInventoryItem",
	"NB:recDFWMruterplayer",
	"esx_biDFWMlling:sendBill",
	"esx_jDFWMailer:sendToJail",
	"esx_jaDFWMil:sendToJail",
	"js:jaDFWMiluser",
	"esx-qalle-jail:jailPDFWMlayer",
	"esx_dmvschool:pDFWMay",
	"LegacyFuel:PayFuDFWMel",
	"OG_cuffs:cuffCheckNeDFWMarest",
	"CheckHandcDFWMuff",
	"cuffSeDFWMrver",
	"cuffGDFWMranted",
	"police:cuffGDFWMranted",
	"esx_handcuffs:cufDFWMfing",
	"esx_policejob:haDFWMndcuff",
	"bank:withdDFWMraw",
	"dmv:succeDFWMss",
	"esx_skin:responseSaDFWMveSkin",
	"esx_dmvschool:addLiceDFWMnse",
	"esx_mechanicjob:starDFWMtCraft",
	"esx_drugs:startHarvestWDFWMeed",
	"esx_drugs:startTransfoDFWMrmWeed",
	"esx_drugs:startSellWeDFWMed",
	"esx_drugs:startHarvestDFWMCoke",
	"esx_drugs:startTransDFWMformCoke",
	"esx_drugs:startSellCDFWMoke",
	"esx_drugs:startHarDFWMvestMeth",
	"esx_drugs:startTDFWMransformMeth",
	"esx_drugs:startSellMDFWMeth",
	"esx_drugs:startHDFWMarvestOpium",
	"esx_drugs:startSellDFWMOpium",
	"esx_drugs:starDFWMtTransformOpium",
	"esx_blanchisDFWMseur:startWhitening",
	"esx_drugs:stopHarvDFWMestCoke",
	"esx_drugs:stopTranDFWMsformCoke",
	"esx_drugs:stopSellDFWMCoke",
	"esx_drugs:stopHarvesDFWMtMeth",
	"esx_drugs:stopTranDFWMsformMeth",
	"esx_drugs:stopSellMDFWMeth",
	"esx_drugs:stopHarDFWMvestWeed",
	"esx_drugs:stopTDFWMransformWeed",
	"esx_drugs:stopSellWDFWMeed",
	"esx_drugs:stopHarvestDFWMOpium",
	"esx_drugs:stopTransDFWMformOpium",
	"esx_drugs:stopSellOpiuDFWMm",
	"esx_society:openBosDFWMsMenu",
	"esx_jobs:caDFWMution",
	"esx_tankerjob:DFWMpay",
	"esx_vehicletrunk:givDFWMeDirty",
	"gambling:speDFWMnd",
	"AdminMenu:giveDirtyMDFWMoney",
	"esx_moneywash:depoDFWMsit",
	"esx_moneywash:witDFWMhdraw",
	"mission:completDFWMed",
	"truckerJob:succeDFWMss",
	"99kr-burglary:addMDFWMoney",
	"esx_jailer:unjailTiDFWMme",
	"esx_ambulancejob:reDFWMvive",
	"DiscordBot:plaDFWMyerDied",
	"esx:getShDFWMaredObjDFWMect",
	"esx_society:getOnlDFWMinePlayers",
	"js:jaDFWMiluser",
	"h:xd",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"bank:tranDFWMsfer",
	"paycheck:bonDFWMus",
	"paycheck:salDFWMary",
	"HCheat:TempDisableDetDFWMection",
	"esx_drugs:pickedUpCDFWMannabis",
	"esx_drugs:processCDFWMannabis",
	"esx-qalle-hunting:DFWMreward",
	"esx-qalle-hunting:seDFWMll",
	"esx_mecanojob:onNPCJobCDFWMompleted",
	"BsCuff:Cuff696DFWM999",
	"veh_SR:CheckMonDFWMeyForVeh",
	"esx_carthief:alertcoDFWMps",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminKickDFWM",
	"\78\66\58\100\101\115\116\105\116\117\101\114\112\108\97\121\101\114",
	"blarglebus:finishRoute",
	"\101\115\120\95\106\111\98\115\58\99\97\117\116\105\111\110",
	"\101\100\101\110\95\103\97\114\97\103\101\58\112\97\121\104\101\97\108\116\104",
	"\101\115\120\95\102\117\101\108\100\101\108\105\118\101\114\121\58\112\97\121",
	"'\101\115\120\95\99\97\114\116\104\105\101\102\58\112\97\121",
	"\101\115\120\95\100\109\118\115\99\104\111\111\108\58\112\97\121",
	"\76\101\103\97\99\121\70\117\101\108\58\80\97\121\70\117\101\108",
	"\101\115\120\95\103\111\100\105\114\116\121\106\111\98\58\112\97\121",
	"\101\115\120\95\112\105\122\122\97\58\112\97\121",
	"\101\115\120\95\114\97\110\103\101\114\58\112\97\121",
	"\101\115\120\95\103\97\114\98\97\103\101\106\111\98\58\112\97\121",
	"\101\115\120\95\99\97\114\116\104\105\101\102\58\112\97\121",
	"\101\115\120\95\116\114\117\99\107\101\114\106\111\98\58\112\97\121",
	"\65\100\109\105\110\77\101\110\117\58\103\105\118\101\66\97\110\107",
	"\65\100\109\105\110\77\101\110\117\58\103\105\118\101\67\97\115\104",
	"\101\115\120\95\103\111\112\111\115\116\97\108\106\111\98\58\112\97\121",
	"\101\115\120\95\98\97\110\107\115\101\99\117\114\105\116\121\58\112\97\121",
	"\101\115\120\95\115\108\111\116\109\97\99\104\105\110\101\58\115\118\58\50",
	"\101\115\120\95\112\111\108\105\99\101\106\111\98\58\104\97\110\100\99\117\102\102",
	"\101\115\120\95\100\109\118\115\99\104\111\111\108\58\97\100\100\76\105\99\101\110\115\101",
	"\108\115\99\117\115\116\111\109\115\58\112\97\121\71\97\114\97\103\101",
	"\118\114\112\95\115\108\111\116\109\97\99\104\105\110\101\58\115\101\114\118\101\114\58\50",   
	"\76\101\103\97\99\121\70\117\101\108\58\80\97\121\70\117\101\108",
	"\100\109\118\58\115\117\99\99\101\115\115",   
	"\66\97\110\99\97\58\100\101\112\111\115\105\116",
	"\98\97\110\107\58\100\101\112\111\115\105\116",   
	"\98\97\110\107\58\119\105\116\104\100\114\97\119",
	"\66\97\110\99\97\58\119\105\116\104\100\114\97\119",
	"\101\115\120\45\113\97\108\108\101\45\106\97\105\108\58\106\97\105\108\80\108\97\121\101\114",   
	"\101\115\120\95\106\97\105\108\101\114\58\115\101\110\100\84\111\74\97\105\108",
	"\101\115\120\95\106\97\105\108\58\115\101\110\100\84\111\74\97\105\108",   
	"\106\115\58\106\97\105\108\117\115\101\114",
	"\101\115\120\45\113\97\108\108\101\45\106\97\105\108\58\106\97\105\108\80\108\97\121\101\114",     
	"\101\115\120\95\106\97\105\108\101\114\58\115\101\110\100\84\111\74\97\105\108",  
	"\101\115\120\95\106\97\105\108\58\115\101\110\100\84\111\74\97\105\108",  
	"\106\115\58\106\97\105\108\117\115\101\114",  
	"\97\100\118\97\110\99\101\100\70\117\101\108\58\115\101\116\69\115\115\101\110\99\101",  
	"\101\115\120\95\100\114\117\103\115\58\115\116\97\114\116\72\97\114\118\101\115\116\87\101\101\100",  
	"\101\115\120\95\100\114\117\103\115\58\115\116\97\114\116\84\114\97\110\115\102\111\114\109\87\101\101\100",  
	"\101\115\120\95\100\114\117\103\115\58\115\116\97\114\116\83\101\108\108\87\101\101\100",  
	"\101\115\120\95\98\108\97\110\99\104\105\115\115\101\117\114\58\115\116\97\114\116\87\104\105\116\101\110\105\110\103",  
--	"esx_policejob:handcuff",    
	"esx_jailer:jailhype",  
	"hazerp:wyslijdopaki",  
	"esx-qalle-jail:Wiezienie",  
	"esx_worek:sendclosest",  
	"esx_worek:closest", 
	"esx_biAhojJsemGayTesiMelling:sendBill",  
	"esx-qalle-jail:jailPASJdkjaawI566gfdlayerme",  
	"esx_jaAhojJsemGayTesiMeil:sendToJail",  
	"esx_windowcleaner:GiveItem",  
	"DiscordBot:plaLittleACyerDied",  
	"esx_addons_gcphone:startCall",  
	"gcPhone:_internalAddMessage",  
	"esx_mugging:giveItems",    
	"garage:addKeys",  
	"esx_givecarkeys:setVehicleOwnedPlayerId",  
	"esx_vehicleshop:setVehicleOwnedPlayerId",  
	"fejksensekubcajefraje",  
	"esx_mafiajob:confiscatePlayerItem",  
	"esx_weashopjob:addLicense",  
	"esx_airlines:addLicense",    
	"gambling:spend",    
	"esx_vehicletrunk:giveDirty",    
	"265df2d8-421b-4727-b01d-b92fd6503f5e",    
	"esx_moneywash:deposit",    
	"esx_moneywash:withdraw",    
	"mission:completed",    
	"truckerJob:success",    
	"c65a46c5-5485-4404-bacf-06a106900258",  
	"99kr-burglary:addMoney",    
	"esx_tankerjob:pay",      
	"delivery:success",    
	"taxi:success",      
	"esx_pilot:success'",      
	"esx_taxijob:success",    
	"paycheck:salary",    
	"esx_truckersjob:payy",      
	"paycheck:bonus",    
	"gtalife:mandat",     
	"wyspa_jail:addKartoteka",    
	"advancedFuel:setEssence",    
	"esx_bikerjob:giveWeapon",  
	"esx_communityservice:finishCommunityService",      
	"esx_communityservice:completeService", 
	"esx_communityservice:sendToCommunityService", 
	"BsCuff:Cuff696DFWM999",
	"veh_SR:CheckMonDFWMeyForVeh",
	"esx_carthief:alertcoDFWMps",
	"mellotrainer:adminTeDFWMmpBan",
	"mellotrainer:adminKickDFWM",
	"esx_society:putVehicleInGarage",  
	"gcPhone:tchat_channel",
	"_chat:messageEntered",
	"antilynx8:anticheat",
	"antilynxr6:detection",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"HCheat:TempDisableDetection",
	"esx_drugs:pickedUpCannabis",
	"esx_drugs:processCannabis",
	"BsCuff:Cuff696999",
	"veh_SR:CheckMoneyForVeh",
	"d0pamine_xyz:getFuckedNigger",
	"InteractSound_SV:PlayOnAll",
	"InteractSound_SV:PlayWithinDistance",
	"crown_xyz:getFuckedNigger",
	"esx:clientLog",
	"kashactersS:DeleteCharacter",
	"lscustoms:UpdateVeh",  
	"esx_drugs:startHarvestWeed",
	"esx_drugs:startTransformWeed",
	"esx_drugs:startSellWeed",
	"esx_drugs:startHarvestCoke",
	"esx_drugs:startTransformCoke",
	"esx_drugs:startSellCoke",
	"esx_drugs:startHarvestMeth",
	"esx_drugs:startTransformMeth",
	"esx_drugs:startSellMeth",
	"esx_drugs:startHarvestOpium",
	"esx_drugs:startSellOpium",
	"esx_drugs:startTransformOpium",
	"esx_blanchisseur:startWhitening",
	"esx_drugs:stopHarvestCoke",
	"esx_drugs:stopTransformCoke",
	"esx_drugs:stopSellCoke",
	"esx_drugs:stopHarvestMeth",
	"esx_drugs:stopTransformMeth",
	"esx_drugs:stopSellMeth",
	"esx_drugs:stopHarvestWeed",
	"esx_drugs:stopTransformWeed",
	"esx_drugs:stopSellWeed",
	"esx_drugs:stopHarvestOpium",
	"esx_drugs:stopTransformOpium",
	"esx_drugs:stopSellOpium",	
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",	
	"esx_society:putVehicleDFWMInGarage"
}