Config = {}

Config.AntiSpectator = true
Config.SpectatorChecking = 10000
Config.SpectatorChecks = true
Config.SpecChecks = 3

Config.AntiGodMode = true
Config.InfinityHealth = false
Config.GodModeChecking = 10000
Config.PlayerMaximumHealth = 200

Config.AntiMaxArmor = true
Config.MaxArmorChecking = 10000
Config.PlayerMaximumArmor = 100

Config.BlockingKeys = false
Config.BlockingKeyInsert = true
Config.BlockingKeyTabQ = true
Config.BlockingKeyShiftG = true
Config.BlockingKeyAltF8 = true
Config.BlockingKeyCtrlF8 = true

Config.CheatEngineBlocking = true
Config.CheatEngineChecking = 6000

Config.InjectionResourceDetecting = true

Config.InjectionGlobalDetecting = true

Config.InjectionCommandDetecting = true

Config.InjectionBCDetecting = true

Config.AntiScreenResult = true

Config.SuspiciousResources = true

Config.SuspiciousResourcesChecking = 25000

Config.InjectionChecking = 25000

Config.BlipCheatBlocking = true
Config.BlipsChecking = 60000

Config.AntiSpawningPeds = true
Config.PedChecking = 60000

Config.AntiAggresivePedsWithWeapons = true

Config.AntiCheatGlobal = true
Config.AntiCheatGlobalChecking = 0

Config.AntiNoClip = true
Config.NoClipChecking = 10000
Config.NoClipBypass = true -- its bypass for example player teleporting
Config.NoClipBypassEventName = "oWd9MnLKdsKv1sJf8iwJKwX0sTJUkrMw" -- How To use it ? Example on player teleport add this event TriggerEvent("oWd9MnLKdsKv1sJf8iwJKwX0sTJUkrMw", true) -- its example for enable bypass and for disable TriggerEvent("oWd9MnLKdsKv1sJf8iwJKwX0sTJUkrMw", false)
Config.NoClipBypassTimedEventName = "ftUzdj4vilUinFLXQykJt6clDlTrsshZ" -- How this method work ? You can give bypass for player for like 5 checkings or 1 checking its up to you, add this event to the teleport function or somewhere where you want TriggerEvent("ftUzdj4vilUinFLXQykJt6clDlTrsshZ", 5) for example i put here number 5 so player get bypass for 5 checkings

Config.AntiTeleport = false
Config.TeleportChecking = 10000
Config.TeleportBypass = true -- its bypass for example player teleporting
Config.TeleportBypassEventName = "TcNSDoLWTCcaS7k1H64mWwFXwaJneu1l" -- How To use it ? Example on player teleport add this event TriggerEvent("TcNSDoLWTCcaS7k1H64mWwFXwaJneu1l", true) -- its example for enable bypass and for disable TriggerEvent("TcNSDoLWTCcaS7k1H64mWwFXwaJneu1l", false)
Config.TeleportBypassTimedEventName = "zgMlK2sQjT1Zo4Td0f2uhtWGQkqAT6aP" -- How this method work ? You can give bypass for player for like 5 checkings or 1 checking its up to you, add this event to the teleport function or somewhere where you want TriggerEvent("zgMlK2sQjT1Zo4Td0f2uhtWGQkqAT6aP", 5) for example i put here number 5 so player get bypass for 5 checkings

Config.AntiInvisible = false
Config.InvisibleChecking = 6000
Config.InvisibleBypass = true -- its bypass for example player instance
Config.InvisibleBypassEventName = "swpM3pbANu9CjoAb9ezcMQ1eyAQoYCC5" -- How To use it ? Example if player on instance add this event TriggerEvent("swpM3pbANu9CjoAb9ezcMQ1eyAQoYCC5", true) -- its example for enable bypass and for disable TriggerEvent("swpM3pbANu9CjoAb9ezcMQ1eyAQoYCC5", false)
Config.InvisibleBypassTimedEventName = "rxQf5Eka8wZ2Y3OAWbAsF8cV8UF2OQjA" -- How this method work ? You can give bypass for player for like 5 checkings or 1 checking its up to you, add this event to the instance function or somewhere where you want TriggerEvent("rxQf5Eka8wZ2Y3OAWbAsF8cV8UF2OQjA", 5) for example i put here number 5 so player get bypass for 5 checkings

Config.AntiSpeedHack = true
Config.SpeedHackValue = 10.0
Config.SpeedChecking = 12000

Config.AntiVehicleRam = true
Config.VehicleRamChecking = 6000

Config.AntiSuperJump = true
Config.AntiSuperJumpChecking = 6000

Config.DetectingTriggeringClientEvents = true

Config.GameTimerChecker = false -- Only Use If you have synchronized time

Config.AntiResourceStopper = true

Config.AntiResourceStarter = true

Config.ScreenshotActions = false
Config.ScreenshotActionsURL = "http://fivem.launchwares.com/upload.php"

Config.NoExplosionDamage = true

Config.AntiRandomStringResource = true
Config.AntiRandomStringResourceChecking = 20000

Config.AntiBlacklistedObjectsSpawn = true
Config.ObjectChecking = 120000

Config.AntiModiferDamage = true

Config.WeaponDamageModiferChecking = 10000

Config.AntiDamageChange = true

Config.AntiWeaponsExplosive = true

Config.AntiNightVision = true
Config.NightVisionChecking = 5000
Config.NightVisionBypass = true
Config.NightVisionBypassEventName = "kebWcqZSkMwK7BXGc2wsHZBflHutFamJ" -- How To use it ? Example on equip night vision on item add this event TriggerEvent("kebWcqZSkMwK7BXGc2wsHZBflHutFamJ", true) -- its example for enable bypass and for disable TriggerEvent("kebWcqZSkMwK7BXGc2wsHZBflHutFamJ", false)

Config.AntiThermalVision = true
Config.ThermalVisionChecking = 5000
Config.ThermalVisionBypass = true
Config.ThermalVisionBypassEventName = "uEfkLhwvGMTVs6vSOPuAub2pxwweB8Yp" -- How To use it ? Example on equip night vision on item add this event TriggerEvent("uEfkLhwvGMTVs6vSOPuAub2pxwweB8Yp", true) -- its example for enable bypass and for disable TriggerEvent("uEfkLhwvGMTVs6vSOPuAub2pxwweB8Yp", false)

Config.AntiVehicleSpawning = true
Config.VehicleSpawningChecking = 3000

Config.AntiVehicleTuning = true
Config.VehicleTuningChecking = 2500
Config.VehicleTuningBypass = true
Config.VehicleTuningBypassEventName = "THn5QFIuS3e8gFYRPTAxtIRXsMYoZFtV" -- How To use it ? Example if player on tuning station add this event TriggerEvent("THn5QFIuS3e8gFYRPTAxtIRXsMYoZFtV", true) -- its example for enable bypass and for disable TriggerEvent("THn5QFIuS3e8gFYRPTAxtIRXsMYoZFtV", false)
Config.VehicleTuningBypassTimedEventName = "KkHl5lJPueLvuFi5p54qlqvJ6OMpikEJ" -- How this method work ? You can give bypass for player for like 5 checkings or 1 checking its up to you, add this event to the tuning function or somewhere where you want TriggerEvent("KkHl5lJPueLvuFi5p54qlqvJ6OMpikEJ", 5) for example i put here number 5 so player get bypass for 5 checkings

Config.BlackListedVehiclePlates = {
	{name = "BRUTAN"},
}

Config.BlacklistedCommands = {
    "chocolate",
    "pk",
    "haha",
    "lol",
    "panickey",
    "killmenu",
    "panik",
    "ssssss",
    "brutan",
    "panic",
    "brutanpremium",
    "hammafia",
	"purgemenu",
    "hamhaxia",
    "redstonia",
    "hoax",
    "desudo",
    "jd",
    "ham",
    "lua options",
    "God Mode",
    "Maestro",
    "FunCtionOk",
    "lynx9_fixed",
    "Fucked",
	"injected",
	"vRP",
	"deleted due to u being a nigger",
	"Dopamine injected successfully",
    "parent menu doesn",
    "www.d0pamine.xyz",
    "d0pamine v1.1 by Nertigel",
	"d0pamine",
	"lynx",
	"FOriv gay",
	"TiagoModz#1478",
	"WarMenu",
	"tiago",
	"TiagoModz",
	"dopamine",
	"dopamina",
	"Nertigel: This server is protected and the menu is not gonna work here.", 
	"Information",
	"[dopamine]",
	"KP",
	"opk",
	"jolmany",
    "SovietH4X",
}

Config.BlackListedClientEvents = {
    "ambulancier:selfRespawn",
    "bank:transfer",
    "esx_ambulancejob:revive",
    "esx-qalle-jail:openJailMenu",
	"esx_inventoryhud:openPlayerInventory",
    "esx_jailer:wysylandoo",
    "esx_society:openBossMenu",
    "esx:spawnVehicle",
    "esx_status:set",
    "HCheat:TempDisableDetection",
    "UnJP",
}

Config.BlacklistedWeaponsForPeds = {
	"WEAPON_KNIFE", 
	"WEAPON_KNUCKLE", 
	--"WEAPON_NIGHTSTICK", 
	--"WEAPON_HAMMER", 
	--"WEAPON_BAT", 
	"WEAPON_GOLFCLUB", 
	"WEAPON_CROWBAR",
	"WEAPON_BOTTLE",
	"WEAPON_DAGGER",
	"WEAPON_HATCHET", 
	"WEAPON_MACHETE",
	"WEAPON_FLASHLIGHT",
	"WEAPON_SWITCHBLADE",
	"WEAPON_PROXMINE", 
	"WEAPON_BZGAS", 
	"WEAPON_SMOKEGRENADE",
	"WEAPON_MOLOTOV",
	"WEAPON_FIREEXTINGUISHER",
	"WEAPON_PETROLCAN",
	"WEAPON_HAZARDCAN",
	"WEAPON_SNOWBALL",
	"WEAPON_FLARE", 
	"WEAPON_BALL", 
	"WEAPON_REVOLVER", 
	"WEAPON_POOLCUE", 
	"WEAPON_PIPEWRENCH", 
	"WEAPON_PISTOL", 
	--"WEAPON_PISTOL_MK2",
	"WEAPON_COMBATPISTOL", 
	"WEAPON_APPISTOL",
	"WEAPON_PISTOL50", 
	"WEAPON_SNSPISTOL", 
	"WEAPON_HEAVYPISTOL", 
	"WEAPON_VINTAGEPISTOL",
	--"WEAPON_STUNGUN", 
	"WEAPON_FLAREGUN",
	"WEAPON_MARKSMANPISTOL", 
	"WEAPON_MICROSMG", 
	"WEAPON_MINISMG",
	--"WEAPON_SMG",
	"WEAPON_SMG_MK2",
	"WEAPON_ASSAULTSMG",
	"WEAPON_MG",
	"WEAPON_COMBATMG",
	"WEAPON_COMBATMG_MK2",
	"WEAPON_COMBATPDW",
	"WEAPON_GUSENBERG",
	"WEAPON_MACHINEPISTOL", 
	"WEAPON_ASSAULTRIFLE",
	"WEAPON_ASSAULTRIFLE_MK2",
	"WEAPON_CARBINERIFLE",
	"WEAPON_CARBINERIFLE_MK2",
	"WEAPON_ADVANCEDRIFLE",
	"WEAPON_SPECIALCARBINE",
	"WEAPON_BULLPUPRIFLE",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_SWEEPERSHOTGUN",
	"WEAPON_SAWNOFFSHOTGUN",
	"WEAPON_BULLPUPSHOTGUN", 
	"WEAPON_ASSAULTSHOTGUN", 
	"WEAPON_MUSKET", 
	"WEAPON_HEAVYSHOTGUN", 
	"WEAPON_DBSHOTGUN", 
	"WEAPON_SNIPERRIFLE", 
	"WEAPON_HEAVYSNIPER", 
	"WEAPON_HEAVYSNIPER_MK2",
	"WEAPON_MARKSMANRIFLE", 
	"WEAPON_GRENADELAUNCHER", 
	"WEAPON_GRENADELAUNCHER_SMOKE", 
	"WEAPON_RPG", 
	"WEAPON_MINIGUN",
	"WEAPON_FIREWORK", 
	"WEAPON_RAILGUN", 
	"WEAPON_HOMINGLAUNCHER", 
	"WEAPON_GRENADE",
	"WEAPON_STICKYBOMB",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_SNSPISTOL_MK2", 
	"WEAPON_REVOLVER_MK2", 
	"WEAPON_DOUBLEACTION",
	"WEAPON_SPECIALCARBINE_MK2",
	"WEAPON_BULLPUPRIFLE_MK2",
	"WEAPON_PUMPSHOTGUN_MK2", 
	"WEAPON_MARKSMANRIFLE_MK2", 
	"WEAPON_RAYPISTOL", 
	"WEAPON_RAYCARBINE", 
	"WEAPON_RAYMINIGUN",
	"WEAPON_DIGISCANNER",
	"WEAPON_NAVYREVOLVER",
	"WEAPON_CERAMICPISTOL",
	"WEAPON_STONE_HATCHET",
	"WEAPON_PIPEBOMB",
	"GADGET_PARACHUTE",
}


Config.WeaponDamages = {
	[-1357824103] = { damage = 34, name = "AdvancedRifle"},
    [453432689] = { damage = 26, name = "Pistol"},
    [1593441988] = { damage = 27, name = "CombatPistol"},
    [584646201] = { damage = 25, name = "APPistol"},
    [-1716589765] = { damage = 51, name = "Pistol50"},
    [-1045183535] = { damage = 160, name = "Revolver"},
    [-1076751822] = { damage = 28, name = "SNSPistol"},
    [-771403250] = { damage = 40, name = "HeavyPistol"},
    [137902532] = { damage = 34, name = "VintagePistol"},
    [324215364] = { damage = 21, name = "MicroSMG"},
    [736523883] = { damage = 22, name = "SMG"},
    [-270015777] = { damage = 23, name = "AssaultSMG"},
    [-1121678507] = { damage = 22, name = "MiniSMG"},
    [-619010992] = { damage = 27, name = "MachinePistol"},
    [171789620] = { damage = 22, name = "CombatPDW"},
    [487013001] = { damage = 58, name = "PumpShotgun"},
    [2017895192] = { damage = 40, name = "SawnoffShotgun"},
    [-494615257] = { damage = 32, name = "AssaultShotgun"},
    [-1654528753] = { damage = 14, name = "BullpupShotgun"},
    [984333226] = { damage = 117, name = "HeavyShotgun"},
    [-1074790547] = { damage = 30, name = "AssaultRifle"},
    [-2084633992] = { damage = 32, name = "CarbineRifle"},
    [-1063057011] = { damage = 32, name = "SpecialCarbine"},
    [2132975508] = { damage = 32, name = "BullpupRifle"},
    [1649403952] = { damage = 34, name = "CompactRifle"},
    [-1660422300] = { damage = 40, name = "MG"},
    [2144741730] = { damage = 45, name = "CombatMG"},
    [1627465347] = { damage = 34, name = "Gusenberg"},
    [100416529] = { damage = 101, name = "SniperRifle"},
    [205991906] = { damage = 216, name = "HeavySniper"},
    [-952879014] = { damage = 65, name = "MarksmanRifle"},
    [1119849093] = { damage = 30, name = "Minigun"},
    [-1466123874] = { damage = 165, name = "Musket"},
    [911657153] = { damage = 1, name = "StunGun"},
    [1198879012] = { damage = 10, name = "FlareGun"},
    [-598887786] = { damage = 220, name = "MarksmanPistol"},
    [1834241177] = { damage = 30, name = "Railgun"},
    [-275439685] = { damage = 30, name = "DoubleBarrelShotgun"},
    [-1746263880] = { damage = 81, name = "Double Action Revolver"},
    [-2009644972] = { damage = 30, name = "SNS Pistol Mk II"},
    [-879347409] = { damage = 200, name = "Heavy Revolver Mk II"},
    [-1768145561] = { damage = 32, name = "Special Carbine Mk II"},
    [-2066285827] = { damage = 33, name = "Bullpup Rifle Mk II"},
    [1432025498] = { damage = 32, name = "Pump Shotgun Mk II"},
    [1785463520] = { damage = 75, name = "Marksman Rifle Mk II"},
    [961495388] = { damage = 40, name = "Assault Rifle Mk II"},
    [-86904375] = { damage = 33, name = "Carbine Rifle Mk II"},
    [-608341376] = { damage = 47, name = "Combat MG Mk II"},
    [177293209] = { damage = 230, name = "Heavy Sniper Mk II"},
    [-1075685676] = { damage = 32, name = "Pistol Mk II"},
    [2024373456] = { damage = 25, name = "SMG Mk II"}
}

Config.BlacklistedPedsClient = {
	"s_m_y_swat_01",
	"u_m_y_juggernaut_01",
	"s_m_m_movalien_01",
	"a_m_y_acult_02",
	"a_m_o_acult_02",
	"a_m_m_acult_02",
	"u_m_m_streetart_01",
	"u_m_y_rsranger_01",
	"u_m_y_pogo_01",
	"ig_orleans",
	"cs_orleans",
	"mp_m_niko_01",
	"s_m_m_movspace_01",
	"mp_m_marston_01",
	"ig_johnnyklebitz",
	"a_c_hen",
	"a_c_sharkhammer",
	"a_c_fish",
	"a_c_deer",
	"a_c_cormorant",
	"a_c_cow",
	"a_c_crow",
	"a_c_chickenhawk",
	"a_c_chimp",
	"cs_bradcadaver",
	"a_c_boar",
	"u_f_m_drowned_01",
	"a_c_sharktiger",
	"a_c_seagull",
	"a_c_rat",
	"a_c_rhesus",
	"a_c_rabbit_01",
	"a_c_pig",
	"a_c_humpback",	
	"u_m_y_zombie_01",
	"a_m_o_acult_01",
	"a_m_m_acult_01",
	"a_m_y_acult_01",
	"ig_wade",
	"s_m_m_paramedic_01",
	"s_m_y_fireman_01",
	"a_m_y_mexthug_01",
	"a_c_cat_01",	
	"a_c_coyote",
	"a_c_dolphin",
	"a_c_killerwhale",
	"a_c_mtlion",	
	"mp_m_freemode_01",	
	"mp_f_freemode_01",
	"a_m_m_skater_01",
	"a_m_y_skater_01",
	"a_m_y_skater_02",
	"a_m_y_hipster_02",
}

Config.BlackListedObjectsClient = {
	{name = "p_crahsed_heli_s"},
	{name = "prop_rock_4_big2"},
	{name = "prop_beachflag_le"},
	{name = "prop_fnclink_05crnr1"},
	{name = "xm_prop_x17_sub"},
	{name = "xs_prop_hamburgher_wl"},
	{name = "xs_prop_plastic_bottle_wl"},
	{name = "prop_windmill_01"},
	{name = "prop_windmill_01_I1"},
	{name = "prop_windmill_01_slod"},
    {name = "prop_windmill_01_slod2"},
    {name = "prop_vintage_pump"},
    {name = "p_spinning_anus_s"},
    {name = "prop_med_jet_01"},
    {name = "prop_box_wood06a"},
    {name = "prop_atm_01"},
    {name = "prop_juicestand"},
    {name = "bkr_prop_bkr_cashpile_04"},
    {name = "prop_bumper_car_01"},
    {name = "lts_prop_lts_elecbox_24"},
    {name = "hei_prop_crate_stack_01"},
    {name = "cs_x_rubweed"},
    {name = "des_fibstair_root"},
    {name = "p_dumpster_t"},
    {name = "p_oil_pjack_02_s"},
    {name = "hei_prop_heist_tug"},
    {name = "p_tram_crash_s"},
    {name = "prop_air_monhut_03_cr"},
    {name = "prop_carwash_roller_vert"},
    {name = "prop_cs_beachtowel_01"},
    {name = "prop_gas_pump_1d"},
    {name = "prop_gas_pump_1b"},
    {name = "prop_gas_pump_old3"},
    {name = "prop_gas_pump_1a"},
    {name = "prop_beach_fire"},
    {name = "prop_ld_toilet_01"},
    {name = "prop_ld_bomb_anim"},
    {name = "prop_ld_farm_couch01"},
    {name = "stt_prop_stunt_track_uturn"},
    {name = "stt_prop_stunt_track_turnice"},
    {name = "stt_prop_stunt_track_hill"},
    {name = "prop_gascyl_01a"},
    {name = "prop_gas_tank_01a"},
    {name = "prop_cs_dildo_01"},
    {name = "v_ilev_gc_weapons"},
    {name = "p_ferris_wheel_amo_l2"},
	{name = "stt_prop_ramp_adj_flip_m"},
	{name = "stt_prop_ramp_adj_flip_mb"},
	{name = "stt_prop_ramp_adj_flip_s"},
	{name = "stt_prop_ramp_adj_flip_sb"},
	{name = "stt_prop_ramp_adj_hloop"},
	{name = "stt_prop_ramp_adj_loop"},
	{name = "stt_prop_ramp_jump_l"},
	{name = "stt_prop_ramp_jump_m"},
	{name = "stt_prop_ramp_jump_s"},
	{name = "stt_prop_ramp_jump_xl"},
	{name = "stt_prop_ramp_jump_xs"},
	{name = "stt_prop_ramp_jump_xxl"},
	{name = "stt_prop_ramp_multi_loop_rb"},
	{name = "stt_prop_ramp_spiral_l"},
	{name = "stt_prop_stunt_soccer_ball"},
	{name = "stt_prop_ramp_spiral_l_l"},
	{name = "stt_prop_ramp_spiral_l_m"},
	{name = "stt_prop_ramp_spiral_l_s"},
	{name = "stt_prop_ramp_spiral_l_xxl"},
	{name = "stt_prop_ramp_spiral_m"},
	{name = "stt_prop_ramp_spiral_s"},
	{name = "stt_prop_ramp_spiral_xxl"},
	{name = "prop_container_01a"},
	{name = "stt_prop_stunt_domino"},
	{name = "stt_prop_stunt_jump15"},
	{name = "stt_prop_stunt_jump30"},
	{name = "stt_prop_stunt_jump45"},
	{name = "stt_prop_stunt_jump_l"},
	{name = "stt_prop_stunt_jump_lb"},
	{name = "stt_prop_stunt_jump_loop"},
	{name = "stt_prop_stunt_jump_m"},
	{name = "stt_prop_stunt_jump_mb"},
	{name = "stt_prop_stunt_jump_s"},
	{name = "stt_prop_stunt_jump_sb"},
	{name = "stt_prop_stunt_landing_zone_01"},
	{name = "stt_prop_stunt_ramp"},
	{name = "stt_prop_stunt_soccer_goal"},
	{name = "stt_prop_stunt_soccer_lball"},
	{name = "stt_prop_stunt_soccer_sball"},
	{name = "stt_prop_stunt_target"},
	{name = "stt_prop_stunt_small"},
	{name = "stt_prop_stunt_track_start"},
	{name = "stt_prop_stunt_track_slope45"},
	{name = "stt_prop_stunt_track_slope30"},
	{name = "stt_prop_stunt_track_slope15"},
	{name = "stt_prop_stunt_track_short"},
	{name = "stt_prop_stunt_track_dwuturn"},
	{name = "stt_prop_stunt_track_dwslope45"},
	{name = "stt_prop_stunt_track_funlng"},
	{name = "stt_prop_stunt_bowling_ball"},
    {name = "stt_prop_stunt_bowling_pin"},
    {name = "imp_prop_ship_01a"},
    {name = "dt1_tc_dufo_core"},
    {name = "db_apart_02_"},
    {name = "xm_prop_iaa_base_elevator"},
    {name = "xs_prop_chips_tube_wl"},
    {name = "prop_weed_01"},
    {name = "sr_prop_spec_tube_xxs_01a"},
    {name = "apa_mp_apa_y3_l2c"},
    {name = "sr_prop_spec_tube_crn_05a"},
    {name = "sr_prop_spec_tube_crn_30d_05a"},
    {name = "sr_prop_spec_tube_l_05a"},
    {name = "sr_prop_spec_tube_m_05a"},
    {name = "sr_prop_spec_tube_xxs_05a"},
    {name = "sr_prop_stunt_tube_crn_15d_05a"},
    {name = "sr_prop_stunt_tube_crn_5d_05a"},
    {name = "sr_prop_stunt_tube_xs_05a"},
    {name = "sr_prop_special_bblock_lrg11"},
    {name = "sr_prop_special_bblock_lrg2"},
    {name = "sr_prop_special_bblock_lrg3"},
    {name = "sr_prop_special_bblock_mdm1"},
    {name = "sr_prop_special_bblock_mdm2"},
    {name = "sr_prop_special_bblock_mdm3"},
    {name = "sr_prop_special_bblock_sml1"},
    {name = "sr_prop_special_bblock_sml2"},
    {name = "sr_prop_special_bblock_sml3"},
    {name = "sr_prop_special_bblock_xl1"},
    {name = "sr_prop_special_bblock_xl2"},
    {name = "sr_prop_special_bblock_xl3"},
    {name = "sr_prop_special_bblock_xl3_fixed"},
    {name = "sr_prop_sr_target_1_01a"},
    {name = "sr_prop_sr_target_2_04a"},
    {name = "sr_prop_sr_target_3_03a"},
    {name = "sr_prop_sr_target_5_01a"},
    {name = "sr_prop_sr_target_large_01a"},
    {name = "sr_prop_sr_target_long_01a"},
    {name = "sr_prop_sr_target_small_01a"},
    {name = "sr_prop_sr_target_small_02a"},
    {name = "sr_prop_sr_target_small_03a"},
    {name = "sr_prop_sr_target_small_04a"},
    {name = "sr_prop_sr_target_small_05a"},
    {name = "sr_prop_sr_target_small_06a"},
    {name = "sr_prop_sr_target_small_07a"},
    {name = "sr_prop_sr_target_trap_01a"},
    {name = "sr_prop_sr_target_trap_02a"},
    {name = "sr_prop_sr_track_block_01"},
    {name = "sr_prop_sr_track_wall"},
    {name = "sr_prop_sr_tube_end"},
    {name = "sr_prop_sr_tube_wall"},
    {name = "sr_prop_spec_target_b_01a"},
    {name = "sr_prop_spec_target_m_01a"},
    {name = "sr_prop_spec_target_s_01a"},
    {name = "sr_prop_spec_tube_refill"},
    {name = "sr_prop_track_refill"},
    {name = "sr_prop_track_refill_t1"},
    {name = "sr_prop_track_refill_t2"},
    {name = "sr_mp_spec_races_ammu_sign"},
    {name = "sr_mp_spec_races_blimp_sign"},
    {name = "sr_mp_spec_races_ron_sign"},
    {name = "sr_mp_spec_races_xero_sign"},
    {name = "sr_prop_sr_start_line_02"},
    {name = "sr_prop_track_straight_l_d15"},
    {name = "sr_prop_track_straight_l_d30"},
    {name = "sr_prop_track_straight_l_d45"},
    {name = "sr_prop_track_straight_l_d5"},
    {name = "sr_prop_track_straight_l_u15"},
    {name = "sr_prop_track_straight_l_u30"},
    {name = "sr_prop_track_straight_l_u45"},
    {name = "sr_prop_track_straight_l_u5"},
    {name = "sr_prop_spec_tube_crn_01a"},
    {name = "sr_prop_spec_tube_crn_30d_01a"},
    {name = "sr_prop_spec_tube_l_01a"},
    {name = "sr_prop_spec_tube_m_01a"},
    {name = "sr_prop_spec_tube_s_01a"},
    {name = "sr_prop_stunt_tube_crn_15d_01a"},
    {name = "sr_prop_stunt_tube_crn_5d_01a"},
    {name = "sr_prop_stunt_tube_crn2_01a"},
    {name = "sr_prop_stunt_tube_xs_01a"},
    {name = "sr_prop_spec_tube_crn_03a"},
    {name = "sr_prop_spec_tube_crn_30d_03a"},
    {name = "sr_prop_spec_tube_l_03a"},
    {name = "sr_prop_spec_tube_m_03a"},
    {name = "sr_prop_spec_tube_s_03a"},
    {name = "sr_prop_spec_tube_xxs_03a"},
    {name = "sr_prop_stunt_tube_crn_15d_03a"},
    {name = "sr_prop_stunt_tube_crn_5d_03a"},
    {name = "sr_prop_stunt_tube_crn2_03a"},
    {name = "sr_prop_stunt_tube_xs_03a"},
    {name = "sr_prop_spec_tube_crn_02a"},
    {name = "sr_prop_spec_tube_crn_30d_02a"},
    {name = "sr_prop_spec_tube_l_02a"},
    {name = "sr_prop_spec_tube_m_02a"},
    {name = "sr_prop_spec_tube_s_02a"},
    {name = "sr_prop_spec_tube_xxs_02a"},
    {name = "sr_prop_stunt_tube_crn_15d_02a"},
    {name = "sr_prop_stunt_tube_crn_5d_02a"},
    {name = "sr_prop_stunt_tube_crn2_02a"},
    {name = "sr_prop_stunt_tube_xs_02a"},
    {name = "sr_prop_spec_tube_crn_04a"},
    {name = "sr_prop_spec_tube_crn_30d_04a"},
    {name = "sr_prop_spec_tube_l_04a"},
    {name = "sr_prop_spec_tube_m_04a"},
    {name = "sr_prop_spec_tube_s_04a"},
    {name = "sr_prop_spec_tube_xxs_04a"},
    {name = "sr_prop_stunt_tube_crn_15d_04a"},
    {name = "sr_prop_stunt_tube_crn_5d_04a"},
    {name = "sr_prop_stunt_tube_crn2_04a"},
    {name = "sr_prop_stunt_tube_xs_04a"},
    {name = "stt_prop_race_tannoy"},
    {name = "stt_prop_speakerstack_01a"},
    {name = "stt_prop_flagpole_1c"},
    {name = "stt_prop_flagpole_1e"},
    {name = "stt_prop_flagpole_1d"},
    {name = "stt_prop_flagpole_1f"},
    {name = "stt_prop_flagpole_1a"},
    {name = "stt_prop_flagpole_1b"},
    {name = "stt_prop_flagpole_2a"},
    {name = "stt_prop_flagpole_2b"},
    {name = "stt_prop_flagpole_2c"},
    {name = "stt_prop_flagpole_2d"},
    {name = "stt_prop_flagpole_2e"},
    {name = "stt_prop_flagpole_2f"},
    {name = "stt_prop_corner_sign_01"},
    {name = "stt_prop_corner_sign_02"},
    {name = "stt_prop_corner_sign_03"},
    {name = "stt_prop_corner_sign_04"},
    {name = "stt_prop_corner_sign_05"},
    {name = "stt_prop_corner_sign_06"},
    {name = "stt_prop_corner_sign_07"},
    {name = "stt_prop_corner_sign_08"},
    {name = "stt_prop_corner_sign_09"},
    {name = "stt_prop_corner_sign_10"},
    {name = "stt_prop_corner_sign_11"},
    {name = "stt_prop_corner_sign_12"},
    {name = "stt_prop_corner_sign_13"},
    {name = "stt_prop_corner_sign_14"},
    {name = "stt_prop_hoop_constraction_01a"},
    {name = "stt_prop_hoop_small_01"},
    {name = "stt_prop_hoop_tyre_01a"},
    {name = "stt_prop_race_gantry_01"},
    {name = "stt_prop_race_start_line_01"},
    {name = "stt_prop_race_start_line_01b"},
    {name = "stt_prop_race_start_line_02b"},
    {name = "stt_prop_race_start_line_03"},
    {name = "stt_prop_race_start_line_03b"},
    {name = "stt_prop_sign_circuit_01"},
    {name = "stt_prop_sign_circuit_02"},
    {name = "stt_prop_sign_circuit_03"},
    {name = "stt_prop_sign_circuit_04"},
    {name = "stt_prop_sign_circuit_05"},
    {name = "stt_prop_sign_circuit_06"},
    {name = "stt_prop_sign_circuit_07"},
    {name = "stt_prop_sign_circuit_08"},
    {name = "stt_prop_sign_circuit_09"},
    {name = "stt_prop_sign_circuit_10"},
    {name = "stt_prop_sign_circuit_11"},
    {name = "stt_prop_sign_circuit_11b"},
    {name = "stt_prop_sign_circuit_12"},
    {name = "stt_prop_sign_circuit_13"},
    {name = "stt_prop_sign_circuit_13b"},
    {name = "stt_prop_sign_circuit_14"},
    {name = "stt_prop_sign_circuit_14b"},
    {name = "stt_prop_sign_circuit_15"},
    {name = "stt_prop_slow_down"},
    {name = "stt_prop_startline_gantry"},
    {name = "stt_prop_stunt_bblock_huge_01"},
    {name = "stt_prop_stunt_bblock_huge_02"},
    {name = "stt_prop_stunt_bblock_huge_03"},
    {name = "stt_prop_stunt_bblock_huge_04"},
    {name = "stt_prop_stunt_bblock_huge_05"},
    {name = "stt_prop_stunt_bblock_hump_01"},
    {name = "stt_prop_stunt_bblock_hump_02"},
    {name = "stt_prop_stunt_bblock_lrg1"},
    {name = "stt_prop_stunt_bblock_lrg2"},
    {name = "stt_prop_stunt_bblock_lrg3"},
    {name = "stt_prop_stunt_bblock_mdm1"},
    {name = "stt_prop_stunt_bblock_mdm2"},
    {name = "stt_prop_stunt_bblock_mdm3"},
    {name = "stt_prop_stunt_bblock_qp"},
    {name = "stt_prop_stunt_bblock_qp2"},
    {name = "stt_prop_stunt_bblock_qp3"},
    {name = "stt_prop_stunt_bblock_sml1"},
    {name = "stt_prop_stunt_bblock_sml2"},
    {name = "stt_prop_stunt_bblock_sml3"},
    {name = "stt_prop_stunt_bblock_xl1"},
    {name = "stt_prop_stunt_bblock_xl2"},
    {name = "stt_prop_stunt_bblock_xl3"},
    {name = "stt_prop_stunt_bowlpin_stand"},
    {name = "stt_prop_stunt_target_small"},
    {name = "stt_prop_stunt_track_bumps"},
    {name = "stt_prop_stunt_track_cutout"},
    {name = "stt_prop_stunt_track_dwlink"},
    {name = "stt_prop_stunt_track_dwlink_02"},
    {name = "stt_prop_stunt_track_dwsh15"},
    {name = "stt_prop_stunt_track_dwshort"},
    {name = "stt_prop_stunt_track_dwslope15"},
    {name = "stt_prop_stunt_track_dwslope30"},
    {name = "stt_prop_stunt_track_dwturn"},
    {name = "stt_prop_stunt_track_exshort"},
    {name = "stt_prop_stunt_track_fork"},
    {name = "stt_prop_stunt_track_funnel"},
    {name = "stt_prop_stunt_track_hill2"},
    {name = "stt_prop_stunt_track_jump"},
    {name = "stt_prop_stunt_track_link"},
    {name = "stt_prop_stunt_track_otake"},
    {name = "stt_prop_stunt_track_sh15"},
    {name = "stt_prop_stunt_track_sh30"},
    {name = "stt_prop_stunt_track_sh45"},
    {name = "stt_prop_stunt_track_sh45_a"},
    {name = "stt_prop_stunt_track_start_02"},
    {name = "stt_prop_stunt_track_straight"},
    {name = "stt_prop_stunt_track_straightice"},
    {name = "stt_prop_stunt_track_st_01"},
    {name = "stt_prop_stunt_track_st_02"},
    {name = "stt_prop_stunt_track_turn"},
    {name = "stt_prop_stunt_tube_crn"},
    {name = "stt_prop_stunt_tube_crn2"},
    {name = "stt_prop_stunt_tube_crn_15d"},
    {name = "stt_prop_stunt_tube_crn_30d"},
    {name = "stt_prop_stunt_tube_crn_5d"},
    {name = "stt_prop_stunt_tube_cross"},
    {name = "stt_prop_stunt_tube_end"},
    {name = "stt_prop_stunt_tube_ent"},
    {name = "stt_prop_stunt_tube_fn_01"},
    {name = "stt_prop_stunt_tube_fn_02"},
    {name = "stt_prop_stunt_tube_fn_03"},
    {name = "stt_prop_stunt_tube_fn_04"},
    {name = "stt_prop_stunt_tube_fn_05"},
    {name = "stt_prop_stunt_tube_fork"},
    {name = "stt_prop_stunt_tube_gap_01"},
    {name = "stt_prop_stunt_tube_gap_02"},
    {name = "stt_prop_stunt_tube_gap_03"},
    {name = "stt_prop_stunt_tube_hg"},
    {name = "stt_prop_stunt_tube_jmp"},
    {name = "stt_prop_stunt_tube_jmp2"},
    {name = "stt_prop_stunt_tube_l"},
    {name = "stt_prop_stunt_tube_m"},
    {name = "stt_prop_stunt_tube_qg"},
    {name = "stt_prop_stunt_tube_s"},
    {name = "stt_prop_stunt_tube_speed"},
    {name = "stt_prop_stunt_tube_speeda"},
    {name = "stt_prop_stunt_tube_speedb"},
    {name = "stt_prop_stunt_tube_xs"},
    {name = "stt_prop_stunt_tube_xxs"},
    {name = "stt_prop_stunt_wideramp"},
    {name = "stt_prop_track_bend2_bar_l"},
    {name = "stt_prop_track_bend2_bar_l_b"},
    {name = "stt_prop_track_bend2_l"},
    {name = "stt_prop_track_bend2_l_b"},
    {name = "stt_prop_track_bend_15d"},
    {name = "stt_prop_track_bend_15d_bar"},
    {name = "stt_prop_track_bend_180d"},
    {name = "stt_prop_track_bend_180d_bar"},
    {name = "stt_prop_track_bend_30d"},
    {name = "stt_prop_track_bend_30d_bar"},
    {name = "stt_prop_track_bend_5d"},
    {name = "stt_prop_track_bend_5d_bar"},
    {name = "stt_prop_track_bend_bar_l"},
    {name = "stt_prop_track_bend_bar_l_b"},
    {name = "stt_prop_track_bend_bar_m"},
    {name = "stt_prop_track_bend_l"},
    {name = "stt_prop_track_bend_l_b"},
    {name = "stt_prop_track_bend_m"},
    {name = "stt_prop_track_block_01"},
    {name = "stt_prop_track_block_02"},
    {name = "stt_prop_track_block_03"},
    {name = "stt_prop_track_chicane_l"},
    {name = "stt_prop_track_chicane_l_02"},
    {name = "stt_prop_track_chicane_r"},
    {name = "stt_prop_track_chicane_r_02"},
    {name = "stt_prop_track_cross"},
    {name = "stt_prop_track_cross_bar"},
    {name = "stt_prop_track_fork"},
    {name = "stt_prop_track_fork_bar"},
    {name = "stt_prop_track_funnel"},
    {name = "stt_prop_track_funnel_ads_01a"},
    {name = "stt_prop_track_funnel_ads_01b"},
    {name = "stt_prop_track_funnel_ads_01c"},
    {name = "stt_prop_track_jump_01a"},
    {name = "stt_prop_track_jump_01b"},
    {name = "stt_prop_track_jump_01c"},
    {name = "stt_prop_track_jump_02a"},
    {name = "stt_prop_track_jump_02b"},
    {name = "stt_prop_track_jump_02c"},
    {name = "stt_prop_track_link"},
    {name = "stt_prop_track_slowdown"},
    {name = "stt_prop_track_slowdown_t1"},
    {name = "stt_prop_track_slowdown_t2"},
    {name = "stt_prop_track_speedup"},
    {name = "stt_prop_track_speedup_t1"},
    {name = "stt_prop_track_speedup_t2"},
    {name = "stt_prop_track_start_02"},
    {name = "stt_prop_track_start"},
    {name = "stt_prop_track_stop_sign"},
    {name = "stt_prop_track_straight_bar_l"},
    {name = "stt_prop_track_straight_bar_m"},
    {name = "stt_prop_track_straight_bar_s"},
    {name = "stt_prop_track_straight_l"},
    {name = "stt_prop_track_straight_lm"},
    {name = "stt_prop_track_straight_lm_bar"},
    {name = "stt_prop_track_straight_m"},
    {name = "stt_prop_track_straight_s"},
    {name = "stt_prop_track_tube_01"},
    {name = "stt_prop_track_tube_02"},
    {name = "stt_prop_tyre_wall_01"},
    {name = "stt_prop_tyre_wall_010"},
    {name = "stt_prop_tyre_wall_011"},
    {name = "stt_prop_tyre_wall_012"},
    {name = "stt_prop_tyre_wall_013"},
    {name = "stt_prop_tyre_wall_014"},
    {name = "stt_prop_tyre_wall_015"},
    {name = "stt_prop_tyre_wall_02"},
    {name = "stt_prop_tyre_wall_03"},
    {name = "stt_prop_tyre_wall_05"},
    {name = "stt_prop_tyre_wall_06"},
    {name = "stt_prop_tyre_wall_07"},
    {name = "stt_prop_tyre_wall_08"},
    {name = "stt_prop_tyre_wall_09"},
    {name = "stt_prop_tyre_wall_0l010"},
    {name = "stt_prop_tyre_wall_0l012"},
    {name = "stt_prop_tyre_wall_0l013"},
    {name = "stt_prop_tyre_wall_0l014"},
    {name = "stt_prop_tyre_wall_0l015"},
    {name = "stt_prop_tyre_wall_0l018"},
    {name = "stt_prop_tyre_wall_0l019"},
    {name = "stt_prop_tyre_wall_0l020"},
    {name = "stt_prop_tyre_wall_0l04"},
    {name = "stt_prop_tyre_wall_0l05"},
    {name = "stt_prop_tyre_wall_0l06"},
    {name = "stt_prop_tyre_wall_0l07"},
    {name = "stt_prop_tyre_wall_0l08"},
    {name = "stt_prop_tyre_wall_0l1"},
    {name = "stt_prop_tyre_wall_0l16"},
    {name = "stt_prop_tyre_wall_0l17"},
    {name = "stt_prop_tyre_wall_0l2"},
    {name = "stt_prop_tyre_wall_0l3"},
    {name = "stt_prop_tyre_wall_0r010"},
    {name = "stt_prop_tyre_wall_0r011"},
    {name = "stt_prop_tyre_wall_0r012"},
    {name = "stt_prop_tyre_wall_0r013"},
    {name = "stt_prop_tyre_wall_0r014"},
    {name = "stt_prop_tyre_wall_0r015"},
    {name = "stt_prop_tyre_wall_0r016"},
    {name = "stt_prop_tyre_wall_0r017"},
    {name = "stt_prop_tyre_wall_0r018"},
    {name = "stt_prop_tyre_wall_0r019"},
    {name = "stt_prop_tyre_wall_0r04"},
    {name = "stt_prop_tyre_wall_0r05"},
    {name = "stt_prop_tyre_wall_0r06"},
    {name = "stt_prop_tyre_wall_0r07"},
    {name = "stt_prop_tyre_wall_0r08"},
    {name = "stt_prop_tyre_wall_0r09"},
    {name = "stt_prop_tyre_wall_0r1"},
    {name = "stt_prop_tyre_wall_0r2"},
    {name = "stt_prop_tyre_wall_0r3"},
    {name = "stt_prop_wallride_01"},
    {name = "stt_prop_wallride_01b"},
    {name = "stt_prop_wallride_02"},
    {name = "stt_prop_wallride_02b"},
    {name = "stt_prop_wallride_04"},
    {name = "stt_prop_wallride_05"},
    {name = "stt_prop_wallride_05b"},
    {name = "stt_prop_wallride_45l"},
    {name = "stt_prop_wallride_45la"},
    {name = "stt_prop_wallride_45r"},
    {name = "stt_prop_wallride_45ra"},
    {name = "stt_prop_wallride_90l"},
    {name = "stt_prop_wallride_90lb"},
    {name = "stt_prop_wallride_90r"},
    {name = "stt_prop_wallride_90rb"},
    {name = "apa_MP_Apa_Yacht"},
    {name = "apa_mp_apa_y1_l1a"},
    {name = "apa_mp_apa_y1_l1b"},
    {name = "apa_mp_apa_y1_l1c"},
    {name = "apa_mp_apa_y1_l1d"},
    {name = "apa_mp_apa_y2_l1a"},
    {name = "apa_mp_apa_y2_l1b"},
    {name = "apa_mp_apa_y2_l1c"},
    {name = "apa_mp_apa_y2_l1d"},
    {name = "apa_mp_apa_y3_l1a"},
    {name = "apa_mp_apa_y3_l1b"},
    {name = "apa_mp_apa_y3_l1c"},
    {name = "apa_mp_apa_y3_l1d"},
    {name = "apa_mp_apa_yacht_o1_rail_a"},
    {name = "apa_mp_apa_yacht_o1_rail_b"},
    {name = "apa_mp_apa_yacht_o2_rail_a"},
    {name = "apa_mp_apa_yacht_o2_rail_b"},
    {name = "apa_mp_apa_yacht_o3_rail_a"},
    {name = "apa_mp_apa_yacht_o3_rail_b"},
    {name = "apa_mp_apa_yacht_option1"},
    {name = "apa_mp_apa_yacht_option1_cola"},
    {name = "apa_mp_apa_yacht_option2"},
    {name = "apa_mp_apa_yacht_option2_cola"},
    {name = "apa_mp_apa_yacht_option2_colb"},
    {name = "apa_mp_apa_yacht_option3"},
    {name = "apa_mp_apa_yacht_option3_cola"},
    {name = "apa_mp_apa_yacht_option3_colb"},
    {name = "apa_mp_apa_yacht_option3_colc"},
    {name = "apa_mp_apa_yacht_option3_cold"},
    {name = "apa_mp_apa_yacht_option3_cole"},
    {name = "apa_MP_Apa_Yacht_Jacuzzi_Cam"},
    {name = "apa_mp_apa_yacht_jacuzzi_ripple003"},
    {name = "apa_mp_apa_yacht_jacuzzi_ripple1"},
    {name = "apa_mp_apa_yacht_radar_01a"},
    {name = "apa_MP_Apa_Yacht_Win"},
	{name = "prop_doghouse_01"},
	{name = "a_m_y_skater_01"},
}