-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- GENERAL:
  ['no_players_nearby']         = 'Keine Spieler in der Nähe',
  ['car_locked']            		= 'Fahrzeug abgeschlossen',
  ['car_unlocked']           		= 'Fahrzeug geöffnet',
  ['no_veh_nearby']            	= 'Kein Fahrzeug in der Nähe',
  ['has_key_false']            	= 'Keine Schlüssel für das Auto',
  ['menu_return']            		= 'Zurück',
  ['police_notify']            	= '^0Aktueller Fahrzeugdiebstahl bei ^3%s^0',
  ['dispatch_name']            	= '^5 Dispatch: ',
  ['lockpick_fail']            	= 'Schlossknacken gescheitert',
  ['lockpick_success']         	= 'Erfolgreich das Schloss ~y~geknackt~s~',
  ['hotwire_fail']          		= 'Kurzschliesen gescheitert, versuchs nochmal',
  ['hotwire_success']         	= 'Erfolgreicher ~y~Kurzschluss~s~',
  ['not_in_drv_seat']         	= 'Du musst im Fahrersitz sitzen',
  ['hotwire_impossible']      	= 'Dieses Fahrzeug braucht keinen Kurzschluss!',
  ['search_impossible']        	= 'Du kannst das Auto nicht durchsuchen',
  ['not_in_a_veh']          		= 'Du sitzt nicht in einem Fahrzeug',
  ['npc_give_keys']         		= 'Du hast ein paar Schlüssel erhalten',
  ['npc_ran_away']           		= 'Die Person ist mit den Schlüssel abgehauen',
  ['cash_found']           			= '~g~$%s~s~ Bargeld gefunden.',
  ['item_found']           			= ' ~b~%sx~s~ ~y~%s~s~ gefunden.',
  ['hotwiring']                 = 'Fahrzeug kurzschließen',
  ['car_search']                = 'Fahrzeug durchsuchen',
  
  -- LOCKSMITH MENU:
  ['open_locksmith']            = '~r~[E]~s~ zum ~y~Schloss machen~s~',
  ['shop_main_title']           = 'Fahrzeug auswählen',
  ['reg_key_title']           	= 'Schlüssel herstellen: $%s',
  ['reg_key_accept']           	= 'Bestätigen',
  ['reg_key_decline']           = 'Abbrechen',
  ['key_reg_accepted']          = 'Neuer Schlüssel für das gewählte Fahrzeug hergestellt',
  ['key_reg_declined']          = 'Schlüsselherstellung für das Fahrzeug abgelehnt',
    
  -- ALARMSHOP MENU:
  ['open_alarmshop']            = '~r~[E]~s~ für ~y~ALARM SHOP~s~',
  ['alarm_main_title']          = 'Auto auswählen',
  ['alarm_grade_0']            	= 'Alarm entfernen',
  ['alarm_grade_1']           	= 'Alarm Stufe I',
  ['alarm_grade_2']           	= 'Alarm Stufe II',
  ['alarm_select_title']        = 'Alarm auswählen',
  ['alarm_already_owned']       = 'Du besitzt diese Stufe des Alarm schon',
  ['alarm_removed']       	  	= 'Du hast den Alarm für das Fahrzeug entfernt',
  ['alarm_I_purchased']       	= 'Du hast den Alarm der Stufe I eingebaut',
  ['alarm_II_purchased']       	= 'Du hast den Alarm der Stufe II eingebaut',
  ['not_enough_money']        	= 'Du hast nicht genug Geld auf der Bank',
  ['remove_not_exist_alarm']    = 'Du kannst keinen Alarm entfernen den du nicht hast.',
  ['smth_went_wrong']           = 'Support kontaktieren, Kennzeichen nicht bekannt',
  
  -- CAR MENU:
  ['car_menu_title']          	= 'Fahrzeugmenü',
  ['your_keys']          		    = 'Deine Schlüssel',
  ['confirm_giving_key']        = 'Bestätigung der Schlüsselübergabe?',
  ['confirm_choice']          	= 'Ja',
  ['decline_choice']          	= 'Nein',
  ['remove_key']          	    = 'Schlüssel entfernen',
  ['insured_cars_title']        = 'Versicherte Autos',
  ['veh_windows_menu']          = 'Fenster Optionen',
  ['veh_door_menu']           	= 'Tür Optionen',
  ['veh_engine_label']          = 'Motor On/Off',
  ['veh_neon_label']          	= 'Neon On/Off',
  ['insurance_menu']          	= 'Versicherte Autos',
  ['no_insured_cars']          	= 'Du hast keine versicherten Autos!',
  ['eng_not_running']          	= 'Der Motor muss laufen!',
  ['veh_door_menu_title']       = 'Tür öffnen/schliessen',
  ['veh_windows_menu_title']    = 'Fenster hoch/runter',
  ['door_hood']      			      = 'Motorhaube',
  ['door_trunk']       		    	= 'Kofferraum',
  ['door_front_left']         	= 'Tür Front (L)',
  ['door_front_right']        	= 'Tür Front (R)',
  ['door_rear_left']       	  	= 'Tür Heck (L)',
  ['door_rear_right']         	= 'Tür Heck (R)',
  ['window_front_r']       	  	= 'Fenster Front (L)',
  ['window_front_l']       	  	= 'Fenster Front(R)',
  ['window_rear_r']       	  	= 'Fenster Heck (L)',
  ['window_rear_l']         		= 'Fenster Heck (R)',
    
  -- YOUR KEYS MENU:
  ['your_keys_title']          	= 'Keine Schlüssel',
  ['keys_lend_give']          	= 'Du hast deine Schlüssel an einen Spieler verliehen',
  ['keys_lend_receive']         = 'Du hast Schlüssel von einem Spieler erhalten',
  ['keys_not_stolen_keys']      = 'Du kannst keine gestohlenen Schlüssel verleihen',
  ['keys_not_copy_keys']        = 'Du kannst Schlüsselkopien nicht verleihen',
  ['cannot_remove_owned_keys']  = 'Du kannst deine eigenen Schlüssel nicht entfernen',
  
}
